// Code generated by protoc-gen-go. DO NOT EDIT.
// source: staking.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StakeRequest struct {
	OrgId                int64    `protobuf:"varint,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Amount               float64  `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StakeRequest) Reset()         { *m = StakeRequest{} }
func (m *StakeRequest) String() string { return proto.CompactTextString(m) }
func (*StakeRequest) ProtoMessage()    {}
func (*StakeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_289e7c8aea278311, []int{0}
}

func (m *StakeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StakeRequest.Unmarshal(m, b)
}
func (m *StakeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StakeRequest.Marshal(b, m, deterministic)
}
func (m *StakeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StakeRequest.Merge(m, src)
}
func (m *StakeRequest) XXX_Size() int {
	return xxx_messageInfo_StakeRequest.Size(m)
}
func (m *StakeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StakeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StakeRequest proto.InternalMessageInfo

func (m *StakeRequest) GetOrgId() int64 {
	if m != nil {
		return m.OrgId
	}
	return 0
}

func (m *StakeRequest) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type StakeResponse struct {
	Status               string           `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	UserProfile          *ProfileResponse `protobuf:"bytes,2,opt,name=user_profile,json=userProfile,proto3" json:"user_profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *StakeResponse) Reset()         { *m = StakeResponse{} }
func (m *StakeResponse) String() string { return proto.CompactTextString(m) }
func (*StakeResponse) ProtoMessage()    {}
func (*StakeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_289e7c8aea278311, []int{1}
}

func (m *StakeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StakeResponse.Unmarshal(m, b)
}
func (m *StakeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StakeResponse.Marshal(b, m, deterministic)
}
func (m *StakeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StakeResponse.Merge(m, src)
}
func (m *StakeResponse) XXX_Size() int {
	return xxx_messageInfo_StakeResponse.Size(m)
}
func (m *StakeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StakeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StakeResponse proto.InternalMessageInfo

func (m *StakeResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *StakeResponse) GetUserProfile() *ProfileResponse {
	if m != nil {
		return m.UserProfile
	}
	return nil
}

type UnstakeRequest struct {
	OrgId                int64    `protobuf:"varint,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnstakeRequest) Reset()         { *m = UnstakeRequest{} }
func (m *UnstakeRequest) String() string { return proto.CompactTextString(m) }
func (*UnstakeRequest) ProtoMessage()    {}
func (*UnstakeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_289e7c8aea278311, []int{2}
}

func (m *UnstakeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnstakeRequest.Unmarshal(m, b)
}
func (m *UnstakeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnstakeRequest.Marshal(b, m, deterministic)
}
func (m *UnstakeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnstakeRequest.Merge(m, src)
}
func (m *UnstakeRequest) XXX_Size() int {
	return xxx_messageInfo_UnstakeRequest.Size(m)
}
func (m *UnstakeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnstakeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnstakeRequest proto.InternalMessageInfo

func (m *UnstakeRequest) GetOrgId() int64 {
	if m != nil {
		return m.OrgId
	}
	return 0
}

type UnstakeResponse struct {
	Status               string           `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	UserProfile          *ProfileResponse `protobuf:"bytes,2,opt,name=user_profile,json=userProfile,proto3" json:"user_profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *UnstakeResponse) Reset()         { *m = UnstakeResponse{} }
func (m *UnstakeResponse) String() string { return proto.CompactTextString(m) }
func (*UnstakeResponse) ProtoMessage()    {}
func (*UnstakeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_289e7c8aea278311, []int{3}
}

func (m *UnstakeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnstakeResponse.Unmarshal(m, b)
}
func (m *UnstakeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnstakeResponse.Marshal(b, m, deterministic)
}
func (m *UnstakeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnstakeResponse.Merge(m, src)
}
func (m *UnstakeResponse) XXX_Size() int {
	return xxx_messageInfo_UnstakeResponse.Size(m)
}
func (m *UnstakeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UnstakeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UnstakeResponse proto.InternalMessageInfo

func (m *UnstakeResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *UnstakeResponse) GetUserProfile() *ProfileResponse {
	if m != nil {
		return m.UserProfile
	}
	return nil
}

type StakingHistoryRequest struct {
	OrgId                int64    `protobuf:"varint,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StakingHistoryRequest) Reset()         { *m = StakingHistoryRequest{} }
func (m *StakingHistoryRequest) String() string { return proto.CompactTextString(m) }
func (*StakingHistoryRequest) ProtoMessage()    {}
func (*StakingHistoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_289e7c8aea278311, []int{4}
}

func (m *StakingHistoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StakingHistoryRequest.Unmarshal(m, b)
}
func (m *StakingHistoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StakingHistoryRequest.Marshal(b, m, deterministic)
}
func (m *StakingHistoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StakingHistoryRequest.Merge(m, src)
}
func (m *StakingHistoryRequest) XXX_Size() int {
	return xxx_messageInfo_StakingHistoryRequest.Size(m)
}
func (m *StakingHistoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StakingHistoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StakingHistoryRequest proto.InternalMessageInfo

func (m *StakingHistoryRequest) GetOrgId() int64 {
	if m != nil {
		return m.OrgId
	}
	return 0
}

type StakingHistoryResponse struct {
	UserProfile          *ProfileResponse `protobuf:"bytes,2,opt,name=user_profile,json=userProfile,proto3" json:"user_profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *StakingHistoryResponse) Reset()         { *m = StakingHistoryResponse{} }
func (m *StakingHistoryResponse) String() string { return proto.CompactTextString(m) }
func (*StakingHistoryResponse) ProtoMessage()    {}
func (*StakingHistoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_289e7c8aea278311, []int{5}
}

func (m *StakingHistoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StakingHistoryResponse.Unmarshal(m, b)
}
func (m *StakingHistoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StakingHistoryResponse.Marshal(b, m, deterministic)
}
func (m *StakingHistoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StakingHistoryResponse.Merge(m, src)
}
func (m *StakingHistoryResponse) XXX_Size() int {
	return xxx_messageInfo_StakingHistoryResponse.Size(m)
}
func (m *StakingHistoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StakingHistoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StakingHistoryResponse proto.InternalMessageInfo

func (m *StakingHistoryResponse) GetUserProfile() *ProfileResponse {
	if m != nil {
		return m.UserProfile
	}
	return nil
}

func init() {
	proto.RegisterType((*StakeRequest)(nil), "api.StakeRequest")
	proto.RegisterType((*StakeResponse)(nil), "api.StakeResponse")
	proto.RegisterType((*UnstakeRequest)(nil), "api.UnstakeRequest")
	proto.RegisterType((*UnstakeResponse)(nil), "api.UnstakeResponse")
	proto.RegisterType((*StakingHistoryRequest)(nil), "api.StakingHistoryRequest")
	proto.RegisterType((*StakingHistoryResponse)(nil), "api.StakingHistoryResponse")
}

func init() { proto.RegisterFile("staking.proto", fileDescriptor_289e7c8aea278311) }

var fileDescriptor_289e7c8aea278311 = []byte{
	// 352 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x92, 0xcf, 0x4e, 0x32, 0x31,
	0x14, 0xc5, 0x33, 0x10, 0xf8, 0xf2, 0x5d, 0xfe, 0x18, 0x2a, 0x10, 0x32, 0x48, 0x24, 0x63, 0x8c,
	0xac, 0x86, 0x04, 0x17, 0xae, 0x5c, 0xab, 0x3b, 0x9d, 0x89, 0x2b, 0x17, 0x58, 0xa4, 0x8e, 0x0d,
	0xd8, 0x3b, 0xb6, 0x1d, 0x13, 0x63, 0xdc, 0xf8, 0x0a, 0x3e, 0x8c, 0x0f, 0xe2, 0x2b, 0xf8, 0x20,
	0x86, 0xb6, 0x12, 0x50, 0x12, 0x8c, 0x89, 0xcb, 0x7b, 0xe6, 0xdc, 0x5f, 0xcf, 0xdc, 0x7b, 0xa1,
	0xa2, 0x34, 0x9d, 0x70, 0x91, 0x84, 0xa9, 0x44, 0x8d, 0x24, 0x4f, 0x53, 0xee, 0x6f, 0x25, 0x88,
	0xc9, 0x94, 0xf5, 0x69, 0xca, 0xfb, 0x54, 0x08, 0xd4, 0x54, 0x73, 0x14, 0xca, 0x5a, 0xfc, 0x4a,
	0x2a, 0xf1, 0x9a, 0x4f, 0x99, 0x2d, 0x83, 0x43, 0x28, 0xc7, 0x9a, 0x4e, 0x58, 0xc4, 0xee, 0x32,
	0xa6, 0x34, 0x69, 0x40, 0x11, 0x65, 0x32, 0xe4, 0xe3, 0x96, 0xd7, 0xf5, 0x7a, 0xf9, 0xa8, 0x80,
	0x32, 0x39, 0x19, 0x93, 0x26, 0x14, 0xe9, 0x2d, 0x66, 0x42, 0xb7, 0x72, 0x5d, 0xaf, 0xe7, 0x45,
	0xae, 0x0a, 0x2e, 0xa1, 0xe2, 0xda, 0x55, 0x8a, 0x42, 0xb1, 0x99, 0x51, 0x69, 0xaa, 0x33, 0x65,
	0xfa, 0xff, 0x47, 0xae, 0x22, 0x07, 0x50, 0xce, 0x14, 0x93, 0x43, 0xf7, 0xba, 0xc1, 0x94, 0x06,
	0xf5, 0x90, 0xa6, 0x3c, 0x3c, 0xb5, 0xda, 0x27, 0x23, 0x2a, 0xcd, 0x9c, 0x4e, 0x0c, 0xf6, 0xa0,
	0x7a, 0x2e, 0xd4, 0xfa, 0x88, 0xc1, 0x08, 0x36, 0xe6, 0xc6, 0xbf, 0x0a, 0x13, 0x42, 0x23, 0xb6,
	0x03, 0x3f, 0xe6, 0x4a, 0xa3, 0x7c, 0x58, 0x93, 0xe9, 0x0c, 0x9a, 0x5f, 0xfd, 0x2e, 0xda, 0x6f,
	0x23, 0x0c, 0x5e, 0x73, 0x50, 0x75, 0xcc, 0x98, 0xc9, 0x7b, 0x7e, 0xc5, 0x48, 0x0c, 0x05, 0xb3,
	0x04, 0x52, 0x33, 0xed, 0x8b, 0xfb, 0xf4, 0xc9, 0xa2, 0x64, 0x79, 0xc1, 0xce, 0xf3, 0xdb, 0xfb,
	0x4b, 0xae, 0x43, 0xda, 0xe6, 0x44, 0xdc, 0x05, 0xf5, 0x1f, 0xed, 0x0f, 0x3c, 0x19, 0x81, 0x91,
	0x0b, 0xf8, 0xe7, 0xc6, 0x49, 0x36, 0x0d, 0x63, 0x79, 0x0b, 0x7e, 0x7d, 0x59, 0x74, 0xe8, 0x5d,
	0x83, 0xde, 0x26, 0x9d, 0xd5, 0xe8, 0xcc, 0x11, 0x15, 0xd4, 0x8e, 0x98, 0x5e, 0x1e, 0x0d, 0xf1,
	0xe7, 0x51, 0xbf, 0xcd, 0xd7, 0x6f, 0xaf, 0xfc, 0xf6, 0xb3, 0x47, 0x6f, 0xac, 0x7d, 0x54, 0x34,
	0x17, 0xbf, 0xff, 0x11, 0x00, 0x00, 0xff, 0xff, 0xd3, 0x1a, 0x2d, 0xc2, 0x34, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StakingServiceClient is the client API for StakingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StakingServiceClient interface {
	Stake(ctx context.Context, in *StakeRequest, opts ...grpc.CallOption) (*StakeResponse, error)
	Unstake(ctx context.Context, in *UnstakeRequest, opts ...grpc.CallOption) (*UnstakeResponse, error)
	GetStakingHistory(ctx context.Context, in *StakingHistoryRequest, opts ...grpc.CallOption) (*StakingHistoryResponse, error)
}

type stakingServiceClient struct {
	cc *grpc.ClientConn
}

func NewStakingServiceClient(cc *grpc.ClientConn) StakingServiceClient {
	return &stakingServiceClient{cc}
}

func (c *stakingServiceClient) Stake(ctx context.Context, in *StakeRequest, opts ...grpc.CallOption) (*StakeResponse, error) {
	out := new(StakeResponse)
	err := c.cc.Invoke(ctx, "/api.StakingService/Stake", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stakingServiceClient) Unstake(ctx context.Context, in *UnstakeRequest, opts ...grpc.CallOption) (*UnstakeResponse, error) {
	out := new(UnstakeResponse)
	err := c.cc.Invoke(ctx, "/api.StakingService/Unstake", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stakingServiceClient) GetStakingHistory(ctx context.Context, in *StakingHistoryRequest, opts ...grpc.CallOption) (*StakingHistoryResponse, error) {
	out := new(StakingHistoryResponse)
	err := c.cc.Invoke(ctx, "/api.StakingService/GetStakingHistory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StakingServiceServer is the server API for StakingService service.
type StakingServiceServer interface {
	Stake(context.Context, *StakeRequest) (*StakeResponse, error)
	Unstake(context.Context, *UnstakeRequest) (*UnstakeResponse, error)
	GetStakingHistory(context.Context, *StakingHistoryRequest) (*StakingHistoryResponse, error)
}

// UnimplementedStakingServiceServer can be embedded to have forward compatible implementations.
type UnimplementedStakingServiceServer struct {
}

func (*UnimplementedStakingServiceServer) Stake(ctx context.Context, req *StakeRequest) (*StakeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stake not implemented")
}
func (*UnimplementedStakingServiceServer) Unstake(ctx context.Context, req *UnstakeRequest) (*UnstakeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Unstake not implemented")
}
func (*UnimplementedStakingServiceServer) GetStakingHistory(ctx context.Context, req *StakingHistoryRequest) (*StakingHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStakingHistory not implemented")
}

func RegisterStakingServiceServer(s *grpc.Server, srv StakingServiceServer) {
	s.RegisterService(&_StakingService_serviceDesc, srv)
}

func _StakingService_Stake_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StakeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StakingServiceServer).Stake(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.StakingService/Stake",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StakingServiceServer).Stake(ctx, req.(*StakeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StakingService_Unstake_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnstakeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StakingServiceServer).Unstake(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.StakingService/Unstake",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StakingServiceServer).Unstake(ctx, req.(*UnstakeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StakingService_GetStakingHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StakingHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StakingServiceServer).GetStakingHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.StakingService/GetStakingHistory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StakingServiceServer).GetStakingHistory(ctx, req.(*StakingHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _StakingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.StakingService",
	HandlerType: (*StakingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Stake",
			Handler:    _StakingService_Stake_Handler,
		},
		{
			MethodName: "Unstake",
			Handler:    _StakingService_Unstake_Handler,
		},
		{
			MethodName: "GetStakingHistory",
			Handler:    _StakingService_GetStakingHistory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "staking.proto",
}
