// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gateway.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetGatewayListRequest struct {
	OrgId                int64    `protobuf:"varint,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGatewayListRequest) Reset()         { *m = GetGatewayListRequest{} }
func (m *GetGatewayListRequest) String() string { return proto.CompactTextString(m) }
func (*GetGatewayListRequest) ProtoMessage()    {}
func (*GetGatewayListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a937782ebbded5, []int{0}
}

func (m *GetGatewayListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGatewayListRequest.Unmarshal(m, b)
}
func (m *GetGatewayListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGatewayListRequest.Marshal(b, m, deterministic)
}
func (m *GetGatewayListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGatewayListRequest.Merge(m, src)
}
func (m *GetGatewayListRequest) XXX_Size() int {
	return xxx_messageInfo_GetGatewayListRequest.Size(m)
}
func (m *GetGatewayListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGatewayListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetGatewayListRequest proto.InternalMessageInfo

func (m *GetGatewayListRequest) GetOrgId() int64 {
	if m != nil {
		return m.OrgId
	}
	return 0
}

type GetGatewayListResponse struct {
	GwList               string           `protobuf:"bytes,1,opt,name=gw_list,json=gwList,proto3" json:"gw_list,omitempty"`
	UserProfile          *ProfileResponse `protobuf:"bytes,2,opt,name=user_profile,json=userProfile,proto3" json:"user_profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetGatewayListResponse) Reset()         { *m = GetGatewayListResponse{} }
func (m *GetGatewayListResponse) String() string { return proto.CompactTextString(m) }
func (*GetGatewayListResponse) ProtoMessage()    {}
func (*GetGatewayListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a937782ebbded5, []int{1}
}

func (m *GetGatewayListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGatewayListResponse.Unmarshal(m, b)
}
func (m *GetGatewayListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGatewayListResponse.Marshal(b, m, deterministic)
}
func (m *GetGatewayListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGatewayListResponse.Merge(m, src)
}
func (m *GetGatewayListResponse) XXX_Size() int {
	return xxx_messageInfo_GetGatewayListResponse.Size(m)
}
func (m *GetGatewayListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGatewayListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetGatewayListResponse proto.InternalMessageInfo

func (m *GetGatewayListResponse) GetGwList() string {
	if m != nil {
		return m.GwList
	}
	return ""
}

func (m *GetGatewayListResponse) GetUserProfile() *ProfileResponse {
	if m != nil {
		return m.UserProfile
	}
	return nil
}

type GetGatewayProfileRequest struct {
	OrgId                int64    `protobuf:"varint,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	GwId                 int64    `protobuf:"varint,2,opt,name=gw_id,json=gwId,proto3" json:"gw_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGatewayProfileRequest) Reset()         { *m = GetGatewayProfileRequest{} }
func (m *GetGatewayProfileRequest) String() string { return proto.CompactTextString(m) }
func (*GetGatewayProfileRequest) ProtoMessage()    {}
func (*GetGatewayProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a937782ebbded5, []int{2}
}

func (m *GetGatewayProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGatewayProfileRequest.Unmarshal(m, b)
}
func (m *GetGatewayProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGatewayProfileRequest.Marshal(b, m, deterministic)
}
func (m *GetGatewayProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGatewayProfileRequest.Merge(m, src)
}
func (m *GetGatewayProfileRequest) XXX_Size() int {
	return xxx_messageInfo_GetGatewayProfileRequest.Size(m)
}
func (m *GetGatewayProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGatewayProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetGatewayProfileRequest proto.InternalMessageInfo

func (m *GetGatewayProfileRequest) GetOrgId() int64 {
	if m != nil {
		return m.OrgId
	}
	return 0
}

func (m *GetGatewayProfileRequest) GetGwId() int64 {
	if m != nil {
		return m.GwId
	}
	return 0
}

type GetGatewayProfileResponse struct {
	GwProfile            string           `protobuf:"bytes,1,opt,name=gw_profile,json=gwProfile,proto3" json:"gw_profile,omitempty"`
	UserProfile          *ProfileResponse `protobuf:"bytes,2,opt,name=user_profile,json=userProfile,proto3" json:"user_profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetGatewayProfileResponse) Reset()         { *m = GetGatewayProfileResponse{} }
func (m *GetGatewayProfileResponse) String() string { return proto.CompactTextString(m) }
func (*GetGatewayProfileResponse) ProtoMessage()    {}
func (*GetGatewayProfileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a937782ebbded5, []int{3}
}

func (m *GetGatewayProfileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGatewayProfileResponse.Unmarshal(m, b)
}
func (m *GetGatewayProfileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGatewayProfileResponse.Marshal(b, m, deterministic)
}
func (m *GetGatewayProfileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGatewayProfileResponse.Merge(m, src)
}
func (m *GetGatewayProfileResponse) XXX_Size() int {
	return xxx_messageInfo_GetGatewayProfileResponse.Size(m)
}
func (m *GetGatewayProfileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGatewayProfileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetGatewayProfileResponse proto.InternalMessageInfo

func (m *GetGatewayProfileResponse) GetGwProfile() string {
	if m != nil {
		return m.GwProfile
	}
	return ""
}

func (m *GetGatewayProfileResponse) GetUserProfile() *ProfileResponse {
	if m != nil {
		return m.UserProfile
	}
	return nil
}

type SetGatewayModeRequest struct {
	OrgId                int64    `protobuf:"varint,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	GwId                 int64    `protobuf:"varint,2,opt,name=gw_id,json=gwId,proto3" json:"gw_id,omitempty"`
	GwMode               string   `protobuf:"bytes,3,opt,name=gw_mode,json=gwMode,proto3" json:"gw_mode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetGatewayModeRequest) Reset()         { *m = SetGatewayModeRequest{} }
func (m *SetGatewayModeRequest) String() string { return proto.CompactTextString(m) }
func (*SetGatewayModeRequest) ProtoMessage()    {}
func (*SetGatewayModeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a937782ebbded5, []int{4}
}

func (m *SetGatewayModeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetGatewayModeRequest.Unmarshal(m, b)
}
func (m *SetGatewayModeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetGatewayModeRequest.Marshal(b, m, deterministic)
}
func (m *SetGatewayModeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetGatewayModeRequest.Merge(m, src)
}
func (m *SetGatewayModeRequest) XXX_Size() int {
	return xxx_messageInfo_SetGatewayModeRequest.Size(m)
}
func (m *SetGatewayModeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetGatewayModeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetGatewayModeRequest proto.InternalMessageInfo

func (m *SetGatewayModeRequest) GetOrgId() int64 {
	if m != nil {
		return m.OrgId
	}
	return 0
}

func (m *SetGatewayModeRequest) GetGwId() int64 {
	if m != nil {
		return m.GwId
	}
	return 0
}

func (m *SetGatewayModeRequest) GetGwMode() string {
	if m != nil {
		return m.GwMode
	}
	return ""
}

type SetGatewayModeResponse struct {
	GwMode               string           `protobuf:"bytes,1,opt,name=gw_mode,json=gwMode,proto3" json:"gw_mode,omitempty"`
	UserProfile          *ProfileResponse `protobuf:"bytes,2,opt,name=user_profile,json=userProfile,proto3" json:"user_profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SetGatewayModeResponse) Reset()         { *m = SetGatewayModeResponse{} }
func (m *SetGatewayModeResponse) String() string { return proto.CompactTextString(m) }
func (*SetGatewayModeResponse) ProtoMessage()    {}
func (*SetGatewayModeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a937782ebbded5, []int{5}
}

func (m *SetGatewayModeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetGatewayModeResponse.Unmarshal(m, b)
}
func (m *SetGatewayModeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetGatewayModeResponse.Marshal(b, m, deterministic)
}
func (m *SetGatewayModeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetGatewayModeResponse.Merge(m, src)
}
func (m *SetGatewayModeResponse) XXX_Size() int {
	return xxx_messageInfo_SetGatewayModeResponse.Size(m)
}
func (m *SetGatewayModeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetGatewayModeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetGatewayModeResponse proto.InternalMessageInfo

func (m *SetGatewayModeResponse) GetGwMode() string {
	if m != nil {
		return m.GwMode
	}
	return ""
}

func (m *SetGatewayModeResponse) GetUserProfile() *ProfileResponse {
	if m != nil {
		return m.UserProfile
	}
	return nil
}

func init() {
	proto.RegisterType((*GetGatewayListRequest)(nil), "api.GetGatewayListRequest")
	proto.RegisterType((*GetGatewayListResponse)(nil), "api.GetGatewayListResponse")
	proto.RegisterType((*GetGatewayProfileRequest)(nil), "api.GetGatewayProfileRequest")
	proto.RegisterType((*GetGatewayProfileResponse)(nil), "api.GetGatewayProfileResponse")
	proto.RegisterType((*SetGatewayModeRequest)(nil), "api.SetGatewayModeRequest")
	proto.RegisterType((*SetGatewayModeResponse)(nil), "api.SetGatewayModeResponse")
}

func init() { proto.RegisterFile("gateway.proto", fileDescriptor_f1a937782ebbded5) }

var fileDescriptor_f1a937782ebbded5 = []byte{
	// 392 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0xcf, 0x4e, 0xea, 0x40,
	0x14, 0xc6, 0xd3, 0x72, 0xe1, 0x86, 0xc3, 0x85, 0xe4, 0x8e, 0x56, 0x6a, 0x15, 0x43, 0xba, 0x22,
	0x2e, 0x4a, 0x82, 0x0b, 0x13, 0x1f, 0x40, 0x42, 0xa2, 0x89, 0x29, 0x5b, 0x13, 0x52, 0xed, 0x38,
	0x8e, 0x62, 0xa7, 0x76, 0x06, 0x1b, 0xb7, 0xbe, 0x82, 0x8f, 0xe6, 0xda, 0x9d, 0x0f, 0x62, 0xe6,
	0x4f, 0xd1, 0x42, 0x75, 0xc1, 0xb2, 0x67, 0xbe, 0xf9, 0x7e, 0xdf, 0x99, 0x73, 0x0a, 0x6d, 0x12,
	0x09, 0x9c, 0x47, 0xcf, 0x41, 0x9a, 0x31, 0xc1, 0x50, 0x2d, 0x4a, 0xa9, 0xb7, 0x4f, 0x18, 0x23,
	0x73, 0x3c, 0x8c, 0x52, 0x3a, 0x8c, 0x92, 0x84, 0x89, 0x48, 0x50, 0x96, 0x70, 0x2d, 0xf1, 0xda,
	0x69, 0xc6, 0x6e, 0xe8, 0x1c, 0xeb, 0x4f, 0x3f, 0x00, 0x67, 0x8c, 0xc5, 0x58, 0xbb, 0x9c, 0x51,
	0x2e, 0x42, 0xfc, 0xb8, 0xc0, 0x5c, 0x20, 0x07, 0x1a, 0x2c, 0x23, 0x33, 0x1a, 0xbb, 0x56, 0xdf,
	0x1a, 0xd4, 0xc2, 0x3a, 0xcb, 0xc8, 0x24, 0xf6, 0xef, 0x60, 0x67, 0x55, 0xcf, 0x53, 0x96, 0x70,
	0x8c, 0xba, 0xf0, 0x97, 0xe4, 0xb3, 0x39, 0xe5, 0x42, 0xdd, 0x68, 0x86, 0x0d, 0x92, 0x4b, 0x01,
	0x3a, 0x86, 0x7f, 0x0b, 0x8e, 0xb3, 0x99, 0x01, 0xbb, 0x76, 0xdf, 0x1a, 0xb4, 0x46, 0xdb, 0x41,
	0x94, 0xd2, 0xe0, 0x42, 0xd7, 0x0a, 0x93, 0xb0, 0x25, 0x95, 0xa6, 0xe8, 0x9f, 0x82, 0xfb, 0xc5,
	0x5a, 0x2a, 0x7f, 0x8b, 0x87, 0xb6, 0xa0, 0x4e, 0x72, 0x59, 0xb5, 0x55, 0xf5, 0x0f, 0xc9, 0x27,
	0xb1, 0xcf, 0x61, 0xb7, 0xc2, 0xc7, 0xc4, 0xee, 0x01, 0x90, 0x7c, 0x99, 0x4d, 0x27, 0x6f, 0x92,
	0xdc, 0xc8, 0x36, 0x0f, 0x7f, 0x09, 0xce, 0x74, 0x09, 0x3d, 0x67, 0xf1, 0x26, 0xc9, 0xcd, 0x9b,
	0x3e, 0xb0, 0x18, 0xbb, 0xb5, 0xe2, 0x4d, 0xa5, 0x97, 0x1c, 0xc3, 0xaa, 0x7b, 0x69, 0x0c, 0xea,
	0x8a, 0xf5, 0xfd, 0xca, 0xc6, 0x9d, 0x8c, 0xde, 0x6d, 0xe8, 0x18, 0xd2, 0x14, 0x67, 0x4f, 0xf4,
	0x1a, 0xa3, 0x5b, 0xe8, 0x94, 0xb7, 0x00, 0x79, 0xca, 0xa7, 0x72, 0x95, 0xbc, 0xbd, 0xca, 0x33,
	0x8d, 0xf2, 0x7b, 0x2f, 0x6f, 0x1f, 0xaf, 0x76, 0x17, 0x39, 0x6a, 0x5f, 0x63, 0x2c, 0xfd, 0x87,
	0x04, 0x8b, 0xb1, 0x5e, 0x1e, 0x01, 0xff, 0xd7, 0x66, 0x87, 0x7a, 0x2b, 0x86, 0xe5, 0xdd, 0xf0,
	0x0e, 0x7e, 0x3a, 0x36, 0xc8, 0xbe, 0x42, 0x7a, 0xc8, 0x5d, 0x43, 0x16, 0x80, 0x7b, 0xe8, 0x94,
	0x9f, 0xd7, 0xf4, 0x57, 0x39, 0x51, 0xd3, 0x5f, 0xf5, 0x3c, 0x0a, 0x98, 0x5f, 0xea, 0x8f, 0x4b,
	0x98, 0x94, 0x9d, 0x58, 0x87, 0x57, 0x0d, 0xf5, 0x27, 0x1e, 0x7d, 0x06, 0x00, 0x00, 0xff, 0xff,
	0x1d, 0x55, 0x4e, 0x7c, 0xcc, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GatewayServiceClient is the client API for GatewayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GatewayServiceClient interface {
	GetGatewayList(ctx context.Context, in *GetGatewayListRequest, opts ...grpc.CallOption) (*GetGatewayListResponse, error)
	GetGatewayProfile(ctx context.Context, in *GetGatewayProfileRequest, opts ...grpc.CallOption) (*GetGatewayProfileResponse, error)
	SetGatewayMode(ctx context.Context, in *SetGatewayModeRequest, opts ...grpc.CallOption) (*SetGatewayModeResponse, error)
}

type gatewayServiceClient struct {
	cc *grpc.ClientConn
}

func NewGatewayServiceClient(cc *grpc.ClientConn) GatewayServiceClient {
	return &gatewayServiceClient{cc}
}

func (c *gatewayServiceClient) GetGatewayList(ctx context.Context, in *GetGatewayListRequest, opts ...grpc.CallOption) (*GetGatewayListResponse, error) {
	out := new(GetGatewayListResponse)
	err := c.cc.Invoke(ctx, "/api.GatewayService/GetGatewayList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) GetGatewayProfile(ctx context.Context, in *GetGatewayProfileRequest, opts ...grpc.CallOption) (*GetGatewayProfileResponse, error) {
	out := new(GetGatewayProfileResponse)
	err := c.cc.Invoke(ctx, "/api.GatewayService/GetGatewayProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) SetGatewayMode(ctx context.Context, in *SetGatewayModeRequest, opts ...grpc.CallOption) (*SetGatewayModeResponse, error) {
	out := new(SetGatewayModeResponse)
	err := c.cc.Invoke(ctx, "/api.GatewayService/SetGatewayMode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GatewayServiceServer is the server API for GatewayService service.
type GatewayServiceServer interface {
	GetGatewayList(context.Context, *GetGatewayListRequest) (*GetGatewayListResponse, error)
	GetGatewayProfile(context.Context, *GetGatewayProfileRequest) (*GetGatewayProfileResponse, error)
	SetGatewayMode(context.Context, *SetGatewayModeRequest) (*SetGatewayModeResponse, error)
}

// UnimplementedGatewayServiceServer can be embedded to have forward compatible implementations.
type UnimplementedGatewayServiceServer struct {
}

func (*UnimplementedGatewayServiceServer) GetGatewayList(ctx context.Context, req *GetGatewayListRequest) (*GetGatewayListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGatewayList not implemented")
}
func (*UnimplementedGatewayServiceServer) GetGatewayProfile(ctx context.Context, req *GetGatewayProfileRequest) (*GetGatewayProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGatewayProfile not implemented")
}
func (*UnimplementedGatewayServiceServer) SetGatewayMode(ctx context.Context, req *SetGatewayModeRequest) (*SetGatewayModeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetGatewayMode not implemented")
}

func RegisterGatewayServiceServer(s *grpc.Server, srv GatewayServiceServer) {
	s.RegisterService(&_GatewayService_serviceDesc, srv)
}

func _GatewayService_GetGatewayList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGatewayListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).GetGatewayList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.GatewayService/GetGatewayList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).GetGatewayList(ctx, req.(*GetGatewayListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_GetGatewayProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGatewayProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).GetGatewayProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.GatewayService/GetGatewayProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).GetGatewayProfile(ctx, req.(*GetGatewayProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_SetGatewayMode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetGatewayModeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).SetGatewayMode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.GatewayService/SetGatewayMode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).SetGatewayMode(ctx, req.(*SetGatewayModeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GatewayService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.GatewayService",
	HandlerType: (*GatewayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetGatewayList",
			Handler:    _GatewayService_GetGatewayList_Handler,
		},
		{
			MethodName: "GetGatewayProfile",
			Handler:    _GatewayService_GetGatewayProfile_Handler,
		},
		{
			MethodName: "SetGatewayMode",
			Handler:    _GatewayService_SetGatewayMode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gateway.proto",
}
