// Code generated by protoc-gen-go. DO NOT EDIT.
// source: super_node.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetSuperNodeActiveMoneyAccountRequest struct {
	MoneyAbbr            Money    `protobuf:"varint,1,opt,name=money_abbr,json=moneyAbbr,proto3,enum=api.Money" json:"money_abbr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSuperNodeActiveMoneyAccountRequest) Reset()         { *m = GetSuperNodeActiveMoneyAccountRequest{} }
func (m *GetSuperNodeActiveMoneyAccountRequest) String() string { return proto.CompactTextString(m) }
func (*GetSuperNodeActiveMoneyAccountRequest) ProtoMessage()    {}
func (*GetSuperNodeActiveMoneyAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_02e142dc5bc4ebd3, []int{0}
}

func (m *GetSuperNodeActiveMoneyAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSuperNodeActiveMoneyAccountRequest.Unmarshal(m, b)
}
func (m *GetSuperNodeActiveMoneyAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSuperNodeActiveMoneyAccountRequest.Marshal(b, m, deterministic)
}
func (m *GetSuperNodeActiveMoneyAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSuperNodeActiveMoneyAccountRequest.Merge(m, src)
}
func (m *GetSuperNodeActiveMoneyAccountRequest) XXX_Size() int {
	return xxx_messageInfo_GetSuperNodeActiveMoneyAccountRequest.Size(m)
}
func (m *GetSuperNodeActiveMoneyAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSuperNodeActiveMoneyAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSuperNodeActiveMoneyAccountRequest proto.InternalMessageInfo

func (m *GetSuperNodeActiveMoneyAccountRequest) GetMoneyAbbr() Money {
	if m != nil {
		return m.MoneyAbbr
	}
	return Money_Ether
}

type GetSuperNodeActiveMoneyAccountResponse struct {
	SupernodeActiveAccount string   `protobuf:"bytes,1,opt,name=supernode_active_account,json=supernodeActiveAccount,proto3" json:"supernode_active_account,omitempty"`
	Error                  string   `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *GetSuperNodeActiveMoneyAccountResponse) Reset() {
	*m = GetSuperNodeActiveMoneyAccountResponse{}
}
func (m *GetSuperNodeActiveMoneyAccountResponse) String() string { return proto.CompactTextString(m) }
func (*GetSuperNodeActiveMoneyAccountResponse) ProtoMessage()    {}
func (*GetSuperNodeActiveMoneyAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_02e142dc5bc4ebd3, []int{1}
}

func (m *GetSuperNodeActiveMoneyAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSuperNodeActiveMoneyAccountResponse.Unmarshal(m, b)
}
func (m *GetSuperNodeActiveMoneyAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSuperNodeActiveMoneyAccountResponse.Marshal(b, m, deterministic)
}
func (m *GetSuperNodeActiveMoneyAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSuperNodeActiveMoneyAccountResponse.Merge(m, src)
}
func (m *GetSuperNodeActiveMoneyAccountResponse) XXX_Size() int {
	return xxx_messageInfo_GetSuperNodeActiveMoneyAccountResponse.Size(m)
}
func (m *GetSuperNodeActiveMoneyAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSuperNodeActiveMoneyAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetSuperNodeActiveMoneyAccountResponse proto.InternalMessageInfo

func (m *GetSuperNodeActiveMoneyAccountResponse) GetSupernodeActiveAccount() string {
	if m != nil {
		return m.SupernodeActiveAccount
	}
	return ""
}

func (m *GetSuperNodeActiveMoneyAccountResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*GetSuperNodeActiveMoneyAccountRequest)(nil), "api.GetSuperNodeActiveMoneyAccountRequest")
	proto.RegisterType((*GetSuperNodeActiveMoneyAccountResponse)(nil), "api.GetSuperNodeActiveMoneyAccountResponse")
}

func init() { proto.RegisterFile("super_node.proto", fileDescriptor_02e142dc5bc4ebd3) }

var fileDescriptor_02e142dc5bc4ebd3 = []byte{
	// 272 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x2e, 0x2d, 0x48,
	0x2d, 0x8a, 0xcf, 0xcb, 0x4f, 0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4e, 0x2c,
	0xc8, 0x94, 0x92, 0x49, 0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0xd5, 0x4f, 0x2c, 0xc8, 0xd4, 0x4f, 0xcc,
	0xcb, 0xcb, 0x2f, 0x49, 0x2c, 0xc9, 0xcc, 0xcf, 0x2b, 0x86, 0x28, 0x91, 0xe2, 0xce, 0xcd, 0xcf,
	0x4b, 0xad, 0x84, 0x70, 0x94, 0x82, 0xb8, 0x54, 0xdd, 0x53, 0x4b, 0x82, 0x41, 0xc6, 0xf8, 0xe5,
	0xa7, 0xa4, 0x3a, 0x26, 0x97, 0x64, 0x96, 0xa5, 0xfa, 0x82, 0x14, 0x38, 0x26, 0x27, 0xe7, 0x97,
	0xe6, 0x95, 0x04, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0x69, 0x72, 0x71, 0x81, 0xf5, 0xc5,
	0x27, 0x26, 0x25, 0x15, 0x49, 0x30, 0x2a, 0x30, 0x6a, 0xf0, 0x19, 0x71, 0xe9, 0x25, 0x16, 0x64,
	0xea, 0x81, 0x55, 0x07, 0x71, 0x82, 0x65, 0x1d, 0x93, 0x92, 0x8a, 0x94, 0x2a, 0xb8, 0xd4, 0x08,
	0x99, 0x59, 0x5c, 0x90, 0x9f, 0x57, 0x9c, 0x2a, 0x64, 0xc1, 0x25, 0x01, 0xf6, 0x01, 0xc8, 0x03,
	0xf1, 0x89, 0x60, 0x75, 0xf1, 0x89, 0x10, 0x35, 0x60, 0x2b, 0x38, 0x83, 0xc4, 0xe0, 0xf2, 0x10,
	0x63, 0xa0, 0x26, 0x08, 0x89, 0x70, 0xb1, 0xba, 0x16, 0x15, 0xe5, 0x17, 0x49, 0x30, 0x81, 0x95,
	0x41, 0x38, 0x46, 0x87, 0x18, 0xb9, 0x04, 0xe0, 0xf6, 0x06, 0xa7, 0x16, 0x95, 0x65, 0x26, 0xa7,
	0x0a, 0xad, 0x65, 0xe4, 0x92, 0xc3, 0xef, 0x1e, 0x21, 0x2d, 0xb0, 0x47, 0x88, 0x0a, 0x08, 0x29,
	0x6d, 0xa2, 0xd4, 0x42, 0x3c, 0xa8, 0x64, 0xd4, 0x74, 0xf9, 0xc9, 0x64, 0x26, 0x1d, 0x21, 0x2d,
	0x70, 0x5c, 0xc0, 0xfd, 0xa2, 0x8f, 0xea, 0x57, 0xfd, 0x6a, 0x44, 0xd0, 0xd6, 0x26, 0xb1, 0x81,
	0x63, 0xc6, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x5a, 0x27, 0x47, 0x09, 0xdd, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SuperNodeServiceClient is the client API for SuperNodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SuperNodeServiceClient interface {
	GetSuperNodeActiveMoneyAccount(ctx context.Context, in *GetSuperNodeActiveMoneyAccountRequest, opts ...grpc.CallOption) (*GetSuperNodeActiveMoneyAccountResponse, error)
}

type superNodeServiceClient struct {
	cc *grpc.ClientConn
}

func NewSuperNodeServiceClient(cc *grpc.ClientConn) SuperNodeServiceClient {
	return &superNodeServiceClient{cc}
}

func (c *superNodeServiceClient) GetSuperNodeActiveMoneyAccount(ctx context.Context, in *GetSuperNodeActiveMoneyAccountRequest, opts ...grpc.CallOption) (*GetSuperNodeActiveMoneyAccountResponse, error) {
	out := new(GetSuperNodeActiveMoneyAccountResponse)
	err := c.cc.Invoke(ctx, "/api.SuperNodeService/GetSuperNodeActiveMoneyAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SuperNodeServiceServer is the server API for SuperNodeService service.
type SuperNodeServiceServer interface {
	GetSuperNodeActiveMoneyAccount(context.Context, *GetSuperNodeActiveMoneyAccountRequest) (*GetSuperNodeActiveMoneyAccountResponse, error)
}

func RegisterSuperNodeServiceServer(s *grpc.Server, srv SuperNodeServiceServer) {
	s.RegisterService(&_SuperNodeService_serviceDesc, srv)
}

func _SuperNodeService_GetSuperNodeActiveMoneyAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSuperNodeActiveMoneyAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SuperNodeServiceServer).GetSuperNodeActiveMoneyAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.SuperNodeService/GetSuperNodeActiveMoneyAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SuperNodeServiceServer).GetSuperNodeActiveMoneyAccount(ctx, req.(*GetSuperNodeActiveMoneyAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SuperNodeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.SuperNodeService",
	HandlerType: (*SuperNodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSuperNodeActiveMoneyAccount",
			Handler:    _SuperNodeService_GetSuperNodeActiveMoneyAccount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "super_node.proto",
}
