// Code generated by protoc-gen-go. DO NOT EDIT.
// source: wallet.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetWalletBalanceRequest struct {
	OrgId                int64    `protobuf:"varint,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetWalletBalanceRequest) Reset()         { *m = GetWalletBalanceRequest{} }
func (m *GetWalletBalanceRequest) String() string { return proto.CompactTextString(m) }
func (*GetWalletBalanceRequest) ProtoMessage()    {}
func (*GetWalletBalanceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b88fd140af4deb6f, []int{0}
}

func (m *GetWalletBalanceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWalletBalanceRequest.Unmarshal(m, b)
}
func (m *GetWalletBalanceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWalletBalanceRequest.Marshal(b, m, deterministic)
}
func (m *GetWalletBalanceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWalletBalanceRequest.Merge(m, src)
}
func (m *GetWalletBalanceRequest) XXX_Size() int {
	return xxx_messageInfo_GetWalletBalanceRequest.Size(m)
}
func (m *GetWalletBalanceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWalletBalanceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetWalletBalanceRequest proto.InternalMessageInfo

func (m *GetWalletBalanceRequest) GetOrgId() int64 {
	if m != nil {
		return m.OrgId
	}
	return 0
}

type GetWalletBalanceResponse struct {
	Balance              float32          `protobuf:"fixed32,1,opt,name=balance,proto3" json:"balance,omitempty"`
	Error                string           `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	UserProfile          *ProfileResponse `protobuf:"bytes,3,opt,name=user_profile,json=userProfile,proto3" json:"user_profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetWalletBalanceResponse) Reset()         { *m = GetWalletBalanceResponse{} }
func (m *GetWalletBalanceResponse) String() string { return proto.CompactTextString(m) }
func (*GetWalletBalanceResponse) ProtoMessage()    {}
func (*GetWalletBalanceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b88fd140af4deb6f, []int{1}
}

func (m *GetWalletBalanceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWalletBalanceResponse.Unmarshal(m, b)
}
func (m *GetWalletBalanceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWalletBalanceResponse.Marshal(b, m, deterministic)
}
func (m *GetWalletBalanceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWalletBalanceResponse.Merge(m, src)
}
func (m *GetWalletBalanceResponse) XXX_Size() int {
	return xxx_messageInfo_GetWalletBalanceResponse.Size(m)
}
func (m *GetWalletBalanceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWalletBalanceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetWalletBalanceResponse proto.InternalMessageInfo

func (m *GetWalletBalanceResponse) GetBalance() float32 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *GetWalletBalanceResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *GetWalletBalanceResponse) GetUserProfile() *ProfileResponse {
	if m != nil {
		return m.UserProfile
	}
	return nil
}

type GetVmxcTxHistoryRequest struct {
	OrgId                int64    `protobuf:"varint,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Offset               int64    `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                int64    `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetVmxcTxHistoryRequest) Reset()         { *m = GetVmxcTxHistoryRequest{} }
func (m *GetVmxcTxHistoryRequest) String() string { return proto.CompactTextString(m) }
func (*GetVmxcTxHistoryRequest) ProtoMessage()    {}
func (*GetVmxcTxHistoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b88fd140af4deb6f, []int{2}
}

func (m *GetVmxcTxHistoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVmxcTxHistoryRequest.Unmarshal(m, b)
}
func (m *GetVmxcTxHistoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVmxcTxHistoryRequest.Marshal(b, m, deterministic)
}
func (m *GetVmxcTxHistoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVmxcTxHistoryRequest.Merge(m, src)
}
func (m *GetVmxcTxHistoryRequest) XXX_Size() int {
	return xxx_messageInfo_GetVmxcTxHistoryRequest.Size(m)
}
func (m *GetVmxcTxHistoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVmxcTxHistoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetVmxcTxHistoryRequest proto.InternalMessageInfo

func (m *GetVmxcTxHistoryRequest) GetOrgId() int64 {
	if m != nil {
		return m.OrgId
	}
	return 0
}

func (m *GetVmxcTxHistoryRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *GetVmxcTxHistoryRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type VmxcTxHistory struct {
	From                 string   `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To                   string   `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	TxType               string   `protobuf:"bytes,3,opt,name=tx_type,json=txType,proto3" json:"tx_type,omitempty"`
	Amount               float32  `protobuf:"fixed32,4,opt,name=amount,proto3" json:"amount,omitempty"`
	CreatedAt            string   `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VmxcTxHistory) Reset()         { *m = VmxcTxHistory{} }
func (m *VmxcTxHistory) String() string { return proto.CompactTextString(m) }
func (*VmxcTxHistory) ProtoMessage()    {}
func (*VmxcTxHistory) Descriptor() ([]byte, []int) {
	return fileDescriptor_b88fd140af4deb6f, []int{3}
}

func (m *VmxcTxHistory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VmxcTxHistory.Unmarshal(m, b)
}
func (m *VmxcTxHistory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VmxcTxHistory.Marshal(b, m, deterministic)
}
func (m *VmxcTxHistory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VmxcTxHistory.Merge(m, src)
}
func (m *VmxcTxHistory) XXX_Size() int {
	return xxx_messageInfo_VmxcTxHistory.Size(m)
}
func (m *VmxcTxHistory) XXX_DiscardUnknown() {
	xxx_messageInfo_VmxcTxHistory.DiscardUnknown(m)
}

var xxx_messageInfo_VmxcTxHistory proto.InternalMessageInfo

func (m *VmxcTxHistory) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *VmxcTxHistory) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *VmxcTxHistory) GetTxType() string {
	if m != nil {
		return m.TxType
	}
	return ""
}

func (m *VmxcTxHistory) GetAmount() float32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *VmxcTxHistory) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

type GetVmxcTxHistoryResponse struct {
	Error                string           `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Count                int64            `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	TxHistory            []*VmxcTxHistory `protobuf:"bytes,3,rep,name=tx_history,json=txHistory,proto3" json:"tx_history,omitempty"`
	UserProfile          *ProfileResponse `protobuf:"bytes,4,opt,name=user_profile,json=userProfile,proto3" json:"user_profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetVmxcTxHistoryResponse) Reset()         { *m = GetVmxcTxHistoryResponse{} }
func (m *GetVmxcTxHistoryResponse) String() string { return proto.CompactTextString(m) }
func (*GetVmxcTxHistoryResponse) ProtoMessage()    {}
func (*GetVmxcTxHistoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b88fd140af4deb6f, []int{4}
}

func (m *GetVmxcTxHistoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVmxcTxHistoryResponse.Unmarshal(m, b)
}
func (m *GetVmxcTxHistoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVmxcTxHistoryResponse.Marshal(b, m, deterministic)
}
func (m *GetVmxcTxHistoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVmxcTxHistoryResponse.Merge(m, src)
}
func (m *GetVmxcTxHistoryResponse) XXX_Size() int {
	return xxx_messageInfo_GetVmxcTxHistoryResponse.Size(m)
}
func (m *GetVmxcTxHistoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVmxcTxHistoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetVmxcTxHistoryResponse proto.InternalMessageInfo

func (m *GetVmxcTxHistoryResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *GetVmxcTxHistoryResponse) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *GetVmxcTxHistoryResponse) GetTxHistory() []*VmxcTxHistory {
	if m != nil {
		return m.TxHistory
	}
	return nil
}

func (m *GetVmxcTxHistoryResponse) GetUserProfile() *ProfileResponse {
	if m != nil {
		return m.UserProfile
	}
	return nil
}

func init() {
	proto.RegisterType((*GetWalletBalanceRequest)(nil), "api.GetWalletBalanceRequest")
	proto.RegisterType((*GetWalletBalanceResponse)(nil), "api.GetWalletBalanceResponse")
	proto.RegisterType((*GetVmxcTxHistoryRequest)(nil), "api.GetVmxcTxHistoryRequest")
	proto.RegisterType((*VmxcTxHistory)(nil), "api.VmxcTxHistory")
	proto.RegisterType((*GetVmxcTxHistoryResponse)(nil), "api.GetVmxcTxHistoryResponse")
}

func init() { proto.RegisterFile("wallet.proto", fileDescriptor_b88fd140af4deb6f) }

var fileDescriptor_b88fd140af4deb6f = []byte{
	// 470 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x95, 0xe3, 0x24, 0x95, 0x27, 0x6d, 0x85, 0x46, 0x81, 0x5a, 0x21, 0x41, 0x91, 0xe1, 0x90,
	0x53, 0x0c, 0xe1, 0xc0, 0x19, 0x2e, 0xc0, 0x0d, 0x2d, 0x15, 0xdc, 0xb0, 0xb6, 0xce, 0x26, 0xac,
	0x64, 0x7b, 0xcc, 0x7a, 0x52, 0x1c, 0x21, 0x2e, 0xf0, 0x09, 0xfc, 0x09, 0xbf, 0xc2, 0x2f, 0xf0,
	0x19, 0x1c, 0x50, 0x76, 0xdd, 0xb4, 0x09, 0x2d, 0xea, 0xcd, 0x6f, 0xbc, 0xfb, 0xde, 0xcc, 0x9b,
	0xb7, 0x70, 0xf8, 0x59, 0x66, 0x99, 0xe2, 0x69, 0x69, 0x88, 0x09, 0x7d, 0x59, 0xea, 0xc1, 0x70,
	0x49, 0xb4, 0xcc, 0x54, 0x2c, 0x4b, 0x1d, 0xcb, 0xa2, 0x20, 0x96, 0xac, 0xa9, 0xa8, 0xdc, 0x91,
	0xc1, 0xb1, 0x2e, 0x58, 0x99, 0x42, 0x66, 0x0e, 0x47, 0x8f, 0xe1, 0xe4, 0xa5, 0xe2, 0xf7, 0x96,
	0xe5, 0x85, 0xcc, 0x64, 0x91, 0x2a, 0xa1, 0x3e, 0xad, 0x54, 0xc5, 0x78, 0x17, 0xba, 0x64, 0x96,
	0x89, 0x9e, 0x87, 0xde, 0xd8, 0x9b, 0xf8, 0xa2, 0x43, 0x66, 0xf9, 0x7a, 0x1e, 0x7d, 0xf7, 0x20,
	0xfc, 0xf7, 0x4a, 0x55, 0x52, 0x51, 0x29, 0x0c, 0xe1, 0xe0, 0xcc, 0x95, 0xec, 0xa5, 0x96, 0xb8,
	0x80, 0xd8, 0x87, 0x8e, 0x32, 0x86, 0x4c, 0xd8, 0x1a, 0x7b, 0x93, 0x40, 0x38, 0x80, 0xcf, 0xe0,
	0x70, 0x55, 0x29, 0x93, 0x94, 0x86, 0x16, 0x3a, 0x53, 0xa1, 0x3f, 0xf6, 0x26, 0xbd, 0x59, 0x7f,
	0x2a, 0x4b, 0x3d, 0x7d, 0xe3, 0x6a, 0x17, 0xdc, 0xa2, 0xb7, 0x39, 0xd9, 0x14, 0xa3, 0x0f, 0xb6,
	0xef, 0x77, 0x79, 0x9d, 0x9e, 0xd6, 0xaf, 0x74, 0xc5, 0x64, 0xd6, 0xff, 0xef, 0x1b, 0xef, 0x41,
	0x97, 0x16, 0x8b, 0x4a, 0xb1, 0xed, 0xc0, 0x17, 0x0d, 0xda, 0x34, 0x96, 0xe9, 0x5c, 0xb3, 0xd5,
	0xf6, 0x85, 0x03, 0x9b, 0x29, 0x8f, 0x76, 0xd8, 0x11, 0xa1, 0xbd, 0x30, 0x94, 0x5b, 0xd2, 0x40,
	0xd8, 0x6f, 0x3c, 0x86, 0x16, 0x53, 0x33, 0x51, 0x8b, 0x09, 0x4f, 0xe0, 0x80, 0xeb, 0x84, 0xd7,
	0xa5, 0x9b, 0x24, 0x10, 0x5d, 0xae, 0x4f, 0xd7, 0xa5, 0xda, 0x88, 0xcb, 0x9c, 0x56, 0x05, 0x87,
	0x6d, 0x6b, 0x4b, 0x83, 0x70, 0x04, 0x90, 0x1a, 0x25, 0x59, 0xcd, 0x13, 0xc9, 0x61, 0xc7, 0xde,
	0x09, 0x9a, 0xca, 0x73, 0x8e, 0x7e, 0x3a, 0xaf, 0xf7, 0xc6, 0x6c, 0xbc, 0xde, 0x3a, 0xea, 0x5d,
	0x75, 0xb4, 0x0f, 0x9d, 0xd4, 0x0a, 0xb9, 0x29, 0x1d, 0xc0, 0x27, 0x00, 0x5c, 0x27, 0x1f, 0x1d,
	0x43, 0xe8, 0x8f, 0xfd, 0x49, 0x6f, 0x86, 0xd6, 0xe5, 0x5d, 0xee, 0x80, 0xb7, 0xf3, 0xee, 0xaf,
	0xa6, 0x7d, 0xcb, 0xd5, 0xcc, 0xfe, 0x78, 0x70, 0xe4, 0xd2, 0xf1, 0x56, 0x99, 0x73, 0x9d, 0x2a,
	0x5c, 0xc1, 0x9d, 0xfd, 0xc4, 0xe0, 0xd0, 0x12, 0xdd, 0x90, 0xbd, 0xc1, 0xe8, 0x86, 0xbf, 0x4e,
	0x2f, 0x7a, 0xf4, 0xed, 0xd7, 0xef, 0x1f, 0xad, 0x07, 0x38, 0xb4, 0x29, 0x77, 0x6f, 0x20, 0x6e,
	0x92, 0x16, 0x7f, 0x71, 0xdb, 0xff, 0x8a, 0x6c, 0x65, 0x77, 0xb7, 0xb8, 0x95, 0xbd, 0x2e, 0x3a,
	0x97, 0xb2, 0xd7, 0x3a, 0x1e, 0x3d, 0xb4, 0xb2, 0x23, 0xbc, 0x7f, 0x55, 0xf6, 0x3c, 0xaf, 0xd3,
	0xf8, 0xd2, 0xdc, 0xb3, 0xae, 0x7d, 0x58, 0x4f, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0x29, 0xa2,
	0x22, 0x5e, 0x9b, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WalletServiceClient is the client API for WalletService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WalletServiceClient interface {
	GetWalletBalance(ctx context.Context, in *GetWalletBalanceRequest, opts ...grpc.CallOption) (*GetWalletBalanceResponse, error)
	GetVmxcTxHistory(ctx context.Context, in *GetVmxcTxHistoryRequest, opts ...grpc.CallOption) (*GetVmxcTxHistoryResponse, error)
}

type walletServiceClient struct {
	cc *grpc.ClientConn
}

func NewWalletServiceClient(cc *grpc.ClientConn) WalletServiceClient {
	return &walletServiceClient{cc}
}

func (c *walletServiceClient) GetWalletBalance(ctx context.Context, in *GetWalletBalanceRequest, opts ...grpc.CallOption) (*GetWalletBalanceResponse, error) {
	out := new(GetWalletBalanceResponse)
	err := c.cc.Invoke(ctx, "/api.WalletService/GetWalletBalance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) GetVmxcTxHistory(ctx context.Context, in *GetVmxcTxHistoryRequest, opts ...grpc.CallOption) (*GetVmxcTxHistoryResponse, error) {
	out := new(GetVmxcTxHistoryResponse)
	err := c.cc.Invoke(ctx, "/api.WalletService/GetVmxcTxHistory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WalletServiceServer is the server API for WalletService service.
type WalletServiceServer interface {
	GetWalletBalance(context.Context, *GetWalletBalanceRequest) (*GetWalletBalanceResponse, error)
	GetVmxcTxHistory(context.Context, *GetVmxcTxHistoryRequest) (*GetVmxcTxHistoryResponse, error)
}

func RegisterWalletServiceServer(s *grpc.Server, srv WalletServiceServer) {
	s.RegisterService(&_WalletService_serviceDesc, srv)
}

func _WalletService_GetWalletBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWalletBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).GetWalletBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.WalletService/GetWalletBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).GetWalletBalance(ctx, req.(*GetWalletBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_GetVmxcTxHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVmxcTxHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).GetVmxcTxHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.WalletService/GetVmxcTxHistory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).GetVmxcTxHistory(ctx, req.(*GetVmxcTxHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _WalletService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.WalletService",
	HandlerType: (*WalletServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetWalletBalance",
			Handler:    _WalletService_GetWalletBalance_Handler,
		},
		{
			MethodName: "GetVmxcTxHistory",
			Handler:    _WalletService_GetVmxcTxHistory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wallet.proto",
}
