// Code generated by protoc-gen-go. DO NOT EDIT.
// source: withdraw.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetWithdrawFeeRequest struct {
	// type of crypto currency
	MoneyAbbr            Money    `protobuf:"varint,1,opt,name=money_abbr,json=moneyAbbr,proto3,enum=api.Money" json:"money_abbr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetWithdrawFeeRequest) Reset()         { *m = GetWithdrawFeeRequest{} }
func (m *GetWithdrawFeeRequest) String() string { return proto.CompactTextString(m) }
func (*GetWithdrawFeeRequest) ProtoMessage()    {}
func (*GetWithdrawFeeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0dd7acb611886fa, []int{0}
}

func (m *GetWithdrawFeeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWithdrawFeeRequest.Unmarshal(m, b)
}
func (m *GetWithdrawFeeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWithdrawFeeRequest.Marshal(b, m, deterministic)
}
func (m *GetWithdrawFeeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWithdrawFeeRequest.Merge(m, src)
}
func (m *GetWithdrawFeeRequest) XXX_Size() int {
	return xxx_messageInfo_GetWithdrawFeeRequest.Size(m)
}
func (m *GetWithdrawFeeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWithdrawFeeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetWithdrawFeeRequest proto.InternalMessageInfo

func (m *GetWithdrawFeeRequest) GetMoneyAbbr() Money {
	if m != nil {
		return m.MoneyAbbr
	}
	return Money_Ether
}

type GetWithdrawFeeResponse struct {
	// Withdraw object.
	WithdrawFee          float32  `protobuf:"fixed32,1,opt,name=withdrawFee,proto3" json:"withdrawFee,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetWithdrawFeeResponse) Reset()         { *m = GetWithdrawFeeResponse{} }
func (m *GetWithdrawFeeResponse) String() string { return proto.CompactTextString(m) }
func (*GetWithdrawFeeResponse) ProtoMessage()    {}
func (*GetWithdrawFeeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0dd7acb611886fa, []int{1}
}

func (m *GetWithdrawFeeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWithdrawFeeResponse.Unmarshal(m, b)
}
func (m *GetWithdrawFeeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWithdrawFeeResponse.Marshal(b, m, deterministic)
}
func (m *GetWithdrawFeeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWithdrawFeeResponse.Merge(m, src)
}
func (m *GetWithdrawFeeResponse) XXX_Size() int {
	return xxx_messageInfo_GetWithdrawFeeResponse.Size(m)
}
func (m *GetWithdrawFeeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWithdrawFeeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetWithdrawFeeResponse proto.InternalMessageInfo

func (m *GetWithdrawFeeResponse) GetWithdrawFee() float32 {
	if m != nil {
		return m.WithdrawFee
	}
	return 0
}

func (m *GetWithdrawFeeResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type WithdrawReqRequest struct {
	OrgId                int64    `protobuf:"varint,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	MoneyAbbr            Money    `protobuf:"varint,2,opt,name=money_abbr,json=moneyAbbr,proto3,enum=api.Money" json:"money_abbr,omitempty"`
	Amount               float32  `protobuf:"fixed32,3,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WithdrawReqRequest) Reset()         { *m = WithdrawReqRequest{} }
func (m *WithdrawReqRequest) String() string { return proto.CompactTextString(m) }
func (*WithdrawReqRequest) ProtoMessage()    {}
func (*WithdrawReqRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0dd7acb611886fa, []int{2}
}

func (m *WithdrawReqRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WithdrawReqRequest.Unmarshal(m, b)
}
func (m *WithdrawReqRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WithdrawReqRequest.Marshal(b, m, deterministic)
}
func (m *WithdrawReqRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithdrawReqRequest.Merge(m, src)
}
func (m *WithdrawReqRequest) XXX_Size() int {
	return xxx_messageInfo_WithdrawReqRequest.Size(m)
}
func (m *WithdrawReqRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WithdrawReqRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WithdrawReqRequest proto.InternalMessageInfo

func (m *WithdrawReqRequest) GetOrgId() int64 {
	if m != nil {
		return m.OrgId
	}
	return 0
}

func (m *WithdrawReqRequest) GetMoneyAbbr() Money {
	if m != nil {
		return m.MoneyAbbr
	}
	return Money_Ether
}

func (m *WithdrawReqRequest) GetAmount() float32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type WithdrawReqResponse struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WithdrawReqResponse) Reset()         { *m = WithdrawReqResponse{} }
func (m *WithdrawReqResponse) String() string { return proto.CompactTextString(m) }
func (*WithdrawReqResponse) ProtoMessage()    {}
func (*WithdrawReqResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0dd7acb611886fa, []int{3}
}

func (m *WithdrawReqResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WithdrawReqResponse.Unmarshal(m, b)
}
func (m *WithdrawReqResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WithdrawReqResponse.Marshal(b, m, deterministic)
}
func (m *WithdrawReqResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithdrawReqResponse.Merge(m, src)
}
func (m *WithdrawReqResponse) XXX_Size() int {
	return xxx_messageInfo_WithdrawReqResponse.Size(m)
}
func (m *WithdrawReqResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WithdrawReqResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WithdrawReqResponse proto.InternalMessageInfo

func (m *WithdrawReqResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *WithdrawReqResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type GetWithdrawHistoryRequest struct {
	OrgId                string   `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Offset               string   `protobuf:"bytes,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                int64    `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetWithdrawHistoryRequest) Reset()         { *m = GetWithdrawHistoryRequest{} }
func (m *GetWithdrawHistoryRequest) String() string { return proto.CompactTextString(m) }
func (*GetWithdrawHistoryRequest) ProtoMessage()    {}
func (*GetWithdrawHistoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0dd7acb611886fa, []int{4}
}

func (m *GetWithdrawHistoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWithdrawHistoryRequest.Unmarshal(m, b)
}
func (m *GetWithdrawHistoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWithdrawHistoryRequest.Marshal(b, m, deterministic)
}
func (m *GetWithdrawHistoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWithdrawHistoryRequest.Merge(m, src)
}
func (m *GetWithdrawHistoryRequest) XXX_Size() int {
	return xxx_messageInfo_GetWithdrawHistoryRequest.Size(m)
}
func (m *GetWithdrawHistoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWithdrawHistoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetWithdrawHistoryRequest proto.InternalMessageInfo

func (m *GetWithdrawHistoryRequest) GetOrgId() string {
	if m != nil {
		return m.OrgId
	}
	return ""
}

func (m *GetWithdrawHistoryRequest) GetOffset() string {
	if m != nil {
		return m.Offset
	}
	return ""
}

func (m *GetWithdrawHistoryRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type WithdrawHistory struct {
	From                 string   `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To                   string   `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Money                Money    `protobuf:"varint,3,opt,name=money,proto3,enum=api.Money" json:"money,omitempty"`
	Amount               float32  `protobuf:"fixed32,4,opt,name=amount,proto3" json:"amount,omitempty"`
	CreatedAt            string   `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WithdrawHistory) Reset()         { *m = WithdrawHistory{} }
func (m *WithdrawHistory) String() string { return proto.CompactTextString(m) }
func (*WithdrawHistory) ProtoMessage()    {}
func (*WithdrawHistory) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0dd7acb611886fa, []int{5}
}

func (m *WithdrawHistory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WithdrawHistory.Unmarshal(m, b)
}
func (m *WithdrawHistory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WithdrawHistory.Marshal(b, m, deterministic)
}
func (m *WithdrawHistory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithdrawHistory.Merge(m, src)
}
func (m *WithdrawHistory) XXX_Size() int {
	return xxx_messageInfo_WithdrawHistory.Size(m)
}
func (m *WithdrawHistory) XXX_DiscardUnknown() {
	xxx_messageInfo_WithdrawHistory.DiscardUnknown(m)
}

var xxx_messageInfo_WithdrawHistory proto.InternalMessageInfo

func (m *WithdrawHistory) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *WithdrawHistory) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *WithdrawHistory) GetMoney() Money {
	if m != nil {
		return m.Money
	}
	return Money_Ether
}

func (m *WithdrawHistory) GetAmount() float32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *WithdrawHistory) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

type GetWithdrawHistoryResponse struct {
	Count                int64              `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	WithdrawHistory      []*WithdrawHistory `protobuf:"bytes,2,rep,name=withdraw_history,json=withdrawHistory,proto3" json:"withdraw_history,omitempty"`
	Error                string             `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GetWithdrawHistoryResponse) Reset()         { *m = GetWithdrawHistoryResponse{} }
func (m *GetWithdrawHistoryResponse) String() string { return proto.CompactTextString(m) }
func (*GetWithdrawHistoryResponse) ProtoMessage()    {}
func (*GetWithdrawHistoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0dd7acb611886fa, []int{6}
}

func (m *GetWithdrawHistoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWithdrawHistoryResponse.Unmarshal(m, b)
}
func (m *GetWithdrawHistoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWithdrawHistoryResponse.Marshal(b, m, deterministic)
}
func (m *GetWithdrawHistoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWithdrawHistoryResponse.Merge(m, src)
}
func (m *GetWithdrawHistoryResponse) XXX_Size() int {
	return xxx_messageInfo_GetWithdrawHistoryResponse.Size(m)
}
func (m *GetWithdrawHistoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWithdrawHistoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetWithdrawHistoryResponse proto.InternalMessageInfo

func (m *GetWithdrawHistoryResponse) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *GetWithdrawHistoryResponse) GetWithdrawHistory() []*WithdrawHistory {
	if m != nil {
		return m.WithdrawHistory
	}
	return nil
}

func (m *GetWithdrawHistoryResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*GetWithdrawFeeRequest)(nil), "api.GetWithdrawFeeRequest")
	proto.RegisterType((*GetWithdrawFeeResponse)(nil), "api.GetWithdrawFeeResponse")
	proto.RegisterType((*WithdrawReqRequest)(nil), "api.WithdrawReqRequest")
	proto.RegisterType((*WithdrawReqResponse)(nil), "api.WithdrawReqResponse")
	proto.RegisterType((*GetWithdrawHistoryRequest)(nil), "api.GetWithdrawHistoryRequest")
	proto.RegisterType((*WithdrawHistory)(nil), "api.WithdrawHistory")
	proto.RegisterType((*GetWithdrawHistoryResponse)(nil), "api.GetWithdrawHistoryResponse")
}

func init() { proto.RegisterFile("withdraw.proto", fileDescriptor_b0dd7acb611886fa) }

var fileDescriptor_b0dd7acb611886fa = []byte{
	// 508 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x54, 0x4f, 0x6f, 0xd3, 0x4e,
	0x10, 0x95, 0xed, 0xda, 0xfa, 0x65, 0x22, 0xa5, 0x3f, 0x0d, 0x49, 0x6a, 0x4c, 0x4b, 0x2d, 0x4b,
	0x48, 0x81, 0x43, 0x22, 0x85, 0x1b, 0x17, 0x54, 0x90, 0xf8, 0x73, 0x40, 0x42, 0xe6, 0xc0, 0x31,
	0xac, 0x93, 0x8d, 0xbb, 0x52, 0xed, 0x75, 0xd7, 0x1b, 0xa2, 0x0a, 0x71, 0xe1, 0xc6, 0x85, 0x0b,
	0x1f, 0x8d, 0x0f, 0xc0, 0x85, 0x0f, 0x82, 0x3a, 0x5e, 0x13, 0xdb, 0x4d, 0x7b, 0xf3, 0xcc, 0xac,
	0xdf, 0x7b, 0xf3, 0xf6, 0xd9, 0x30, 0xd8, 0x0a, 0x7d, 0xbe, 0x52, 0x6c, 0x3b, 0x2d, 0x94, 0xd4,
	0x12, 0x1d, 0x56, 0x88, 0xe0, 0x38, 0x95, 0x32, 0xbd, 0xe0, 0x33, 0x56, 0x88, 0x19, 0xcb, 0x73,
	0xa9, 0x99, 0x16, 0x32, 0x2f, 0xab, 0x23, 0x41, 0x3f, 0x93, 0x39, 0xbf, 0xaa, 0x8a, 0xe8, 0x05,
	0x8c, 0x5e, 0x73, 0xfd, 0xd1, 0x80, 0xbc, 0xe2, 0x3c, 0xe6, 0x97, 0x1b, 0x5e, 0x6a, 0x7c, 0x0c,
	0x40, 0xe7, 0x16, 0x2c, 0x49, 0x94, 0x6f, 0x85, 0xd6, 0x64, 0x30, 0x87, 0x29, 0x2b, 0xc4, 0xf4,
	0xdd, 0x75, 0x3b, 0xee, 0xd1, 0xf4, 0x2c, 0x49, 0x54, 0xf4, 0x1e, 0xc6, 0x5d, 0x8c, 0xb2, 0x90,
	0x79, 0xc9, 0x31, 0x84, 0xfe, 0x76, 0xd7, 0x26, 0x14, 0x3b, 0x6e, 0xb6, 0x70, 0x08, 0x2e, 0x57,
	0x4a, 0x2a, 0xdf, 0x0e, 0xad, 0x49, 0x2f, 0xae, 0x8a, 0x28, 0x07, 0xac, 0xe1, 0x62, 0x7e, 0x59,
	0x4b, 0x1a, 0x81, 0x27, 0x55, 0xba, 0x10, 0x2b, 0x02, 0x72, 0x62, 0x57, 0xaa, 0xf4, 0xed, 0xaa,
	0xa3, 0xd4, 0xbe, 0x43, 0x29, 0x8e, 0xc1, 0x63, 0x99, 0xdc, 0xe4, 0xda, 0x77, 0x48, 0x8a, 0xa9,
	0xa2, 0x97, 0x70, 0xaf, 0xc5, 0x67, 0xe4, 0x8f, 0xc1, 0x2b, 0x35, 0xd3, 0x9b, 0x92, 0x08, 0xff,
	0x8b, 0x4d, 0x75, 0x8b, 0xe8, 0x4f, 0x70, 0xbf, 0x61, 0xc3, 0x1b, 0x51, 0x6a, 0xa9, 0xae, 0xf6,
	0x6b, 0xef, 0xd5, 0xda, 0xc7, 0xe0, 0xc9, 0xf5, 0xba, 0xe4, 0xda, 0x40, 0x99, 0xea, 0x9a, 0xe1,
	0x42, 0x64, 0xa2, 0xd2, 0xe9, 0xc4, 0x55, 0x11, 0xfd, 0xb0, 0xe0, 0xb0, 0x83, 0x8f, 0x08, 0x07,
	0x6b, 0x25, 0x33, 0x03, 0x4b, 0xcf, 0x38, 0x00, 0x5b, 0x4b, 0x83, 0x68, 0x6b, 0x89, 0x21, 0xb8,
	0xe4, 0x01, 0xa1, 0xb5, 0xcd, 0xa9, 0x06, 0x0d, 0x63, 0x0e, 0x9a, 0xc6, 0xe0, 0x09, 0xc0, 0x52,
	0x71, 0xa6, 0xf9, 0x6a, 0xc1, 0xb4, 0xef, 0x12, 0x62, 0xcf, 0x74, 0xce, 0x74, 0xf4, 0xdd, 0x82,
	0x60, 0xdf, 0xce, 0xc6, 0xbf, 0x21, 0xb8, 0x4b, 0x02, 0x35, 0xf7, 0x45, 0x05, 0x3e, 0x87, 0xff,
	0xeb, 0x04, 0x2c, 0xce, 0xab, 0x37, 0x7c, 0x3b, 0x74, 0x26, 0xfd, 0xf9, 0x90, 0x84, 0x75, 0xd1,
	0x0e, 0xb7, 0x9d, 0x95, 0xff, 0xd9, 0xef, 0x34, 0xec, 0x9f, 0xff, 0xb6, 0x77, 0xe6, 0x7c, 0xe0,
	0xea, 0xb3, 0x58, 0x72, 0xcc, 0x60, 0xd0, 0x4e, 0x26, 0x06, 0x44, 0xb1, 0x37, 0xf2, 0xc1, 0x83,
	0xbd, 0xb3, 0x6a, 0x97, 0x28, 0xfa, 0xf6, 0xeb, 0xcf, 0x4f, 0xfb, 0x18, 0x03, 0xfa, 0xaa, 0x6a,
	0x49, 0xb3, 0x2f, 0xbb, 0xe8, 0x7d, 0xc5, 0x14, 0xfa, 0x8d, 0x18, 0xe1, 0x51, 0x6b, 0x9d, 0x5d,
	0x90, 0x03, 0xff, 0xe6, 0xc0, 0xb0, 0x3c, 0x22, 0x96, 0xd3, 0xe8, 0x0e, 0x96, 0x67, 0xd6, 0x13,
	0xd4, 0x80, 0x37, 0x6d, 0xc7, 0x87, 0x5d, 0xfd, 0xed, 0x0c, 0x06, 0xa7, 0xb7, 0xce, 0x0d, 0xfb,
	0x09, 0xb1, 0x1f, 0xe1, 0xa8, 0xcd, 0x6e, 0x2e, 0x29, 0xf1, 0xe8, 0x97, 0xf1, 0xf4, 0x6f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x41, 0x76, 0xdb, 0x23, 0x74, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WithdrawServiceClient is the client API for WithdrawService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WithdrawServiceClient interface {
	// Get data for current withdraw fee
	GetWithdrawFee(ctx context.Context, in *GetWithdrawFeeRequest, opts ...grpc.CallOption) (*GetWithdrawFeeResponse, error)
	WithdrawReq(ctx context.Context, in *WithdrawReqRequest, opts ...grpc.CallOption) (*WithdrawReqResponse, error)
	GetWithdrawHistory(ctx context.Context, in *GetWithdrawHistoryRequest, opts ...grpc.CallOption) (*GetWithdrawHistoryResponse, error)
}

type withdrawServiceClient struct {
	cc *grpc.ClientConn
}

func NewWithdrawServiceClient(cc *grpc.ClientConn) WithdrawServiceClient {
	return &withdrawServiceClient{cc}
}

func (c *withdrawServiceClient) GetWithdrawFee(ctx context.Context, in *GetWithdrawFeeRequest, opts ...grpc.CallOption) (*GetWithdrawFeeResponse, error) {
	out := new(GetWithdrawFeeResponse)
	err := c.cc.Invoke(ctx, "/api.WithdrawService/GetWithdrawFee", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *withdrawServiceClient) WithdrawReq(ctx context.Context, in *WithdrawReqRequest, opts ...grpc.CallOption) (*WithdrawReqResponse, error) {
	out := new(WithdrawReqResponse)
	err := c.cc.Invoke(ctx, "/api.WithdrawService/WithdrawReq", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *withdrawServiceClient) GetWithdrawHistory(ctx context.Context, in *GetWithdrawHistoryRequest, opts ...grpc.CallOption) (*GetWithdrawHistoryResponse, error) {
	out := new(GetWithdrawHistoryResponse)
	err := c.cc.Invoke(ctx, "/api.WithdrawService/GetWithdrawHistory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WithdrawServiceServer is the server API for WithdrawService service.
type WithdrawServiceServer interface {
	// Get data for current withdraw fee
	GetWithdrawFee(context.Context, *GetWithdrawFeeRequest) (*GetWithdrawFeeResponse, error)
	WithdrawReq(context.Context, *WithdrawReqRequest) (*WithdrawReqResponse, error)
	GetWithdrawHistory(context.Context, *GetWithdrawHistoryRequest) (*GetWithdrawHistoryResponse, error)
}

func RegisterWithdrawServiceServer(s *grpc.Server, srv WithdrawServiceServer) {
	s.RegisterService(&_WithdrawService_serviceDesc, srv)
}

func _WithdrawService_GetWithdrawFee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWithdrawFeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WithdrawServiceServer).GetWithdrawFee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.WithdrawService/GetWithdrawFee",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WithdrawServiceServer).GetWithdrawFee(ctx, req.(*GetWithdrawFeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WithdrawService_WithdrawReq_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WithdrawReqRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WithdrawServiceServer).WithdrawReq(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.WithdrawService/WithdrawReq",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WithdrawServiceServer).WithdrawReq(ctx, req.(*WithdrawReqRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WithdrawService_GetWithdrawHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWithdrawHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WithdrawServiceServer).GetWithdrawHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.WithdrawService/GetWithdrawHistory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WithdrawServiceServer).GetWithdrawHistory(ctx, req.(*GetWithdrawHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _WithdrawService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.WithdrawService",
	HandlerType: (*WithdrawServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetWithdrawFee",
			Handler:    _WithdrawService_GetWithdrawFee_Handler,
		},
		{
			MethodName: "WithdrawReq",
			Handler:    _WithdrawService_WithdrawReq_Handler,
		},
		{
			MethodName: "GetWithdrawHistory",
			Handler:    _WithdrawService_GetWithdrawHistory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "withdraw.proto",
}
