// Code generated by protoc-gen-go. DO NOT EDIT.
// source: inner_gateway.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AppServerGatewayProfile struct {
	Mac                  string   `protobuf:"bytes,1,opt,name=mac,proto3" json:"mac,omitempty"`
	CreateAt             string   `protobuf:"bytes,2,opt,name=create_at,json=createAt,proto3" json:"create_at,omitempty"`
	LastSeenAt           string   `protobuf:"bytes,3,opt,name=last_seen_at,json=lastSeenAt,proto3" json:"last_seen_at,omitempty"`
	OrgId                int64    `protobuf:"varint,4,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Description          string   `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Name                 string   `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppServerGatewayProfile) Reset()         { *m = AppServerGatewayProfile{} }
func (m *AppServerGatewayProfile) String() string { return proto.CompactTextString(m) }
func (*AppServerGatewayProfile) ProtoMessage()    {}
func (*AppServerGatewayProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_19e05f446ec45efc, []int{0}
}

func (m *AppServerGatewayProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppServerGatewayProfile.Unmarshal(m, b)
}
func (m *AppServerGatewayProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppServerGatewayProfile.Marshal(b, m, deterministic)
}
func (m *AppServerGatewayProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppServerGatewayProfile.Merge(m, src)
}
func (m *AppServerGatewayProfile) XXX_Size() int {
	return xxx_messageInfo_AppServerGatewayProfile.Size(m)
}
func (m *AppServerGatewayProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_AppServerGatewayProfile.DiscardUnknown(m)
}

var xxx_messageInfo_AppServerGatewayProfile proto.InternalMessageInfo

func (m *AppServerGatewayProfile) GetMac() string {
	if m != nil {
		return m.Mac
	}
	return ""
}

func (m *AppServerGatewayProfile) GetCreateAt() string {
	if m != nil {
		return m.CreateAt
	}
	return ""
}

func (m *AppServerGatewayProfile) GetLastSeenAt() string {
	if m != nil {
		return m.LastSeenAt
	}
	return ""
}

func (m *AppServerGatewayProfile) GetOrgId() int64 {
	if m != nil {
		return m.OrgId
	}
	return 0
}

func (m *AppServerGatewayProfile) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *AppServerGatewayProfile) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type AddGatewayInM2MServerRequest struct {
	OrgId                int64                      `protobuf:"varint,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	GwProfile            []*AppServerGatewayProfile `protobuf:"bytes,2,rep,name=gw_profile,json=gwProfile,proto3" json:"gw_profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *AddGatewayInM2MServerRequest) Reset()         { *m = AddGatewayInM2MServerRequest{} }
func (m *AddGatewayInM2MServerRequest) String() string { return proto.CompactTextString(m) }
func (*AddGatewayInM2MServerRequest) ProtoMessage()    {}
func (*AddGatewayInM2MServerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_19e05f446ec45efc, []int{1}
}

func (m *AddGatewayInM2MServerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddGatewayInM2MServerRequest.Unmarshal(m, b)
}
func (m *AddGatewayInM2MServerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddGatewayInM2MServerRequest.Marshal(b, m, deterministic)
}
func (m *AddGatewayInM2MServerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddGatewayInM2MServerRequest.Merge(m, src)
}
func (m *AddGatewayInM2MServerRequest) XXX_Size() int {
	return xxx_messageInfo_AddGatewayInM2MServerRequest.Size(m)
}
func (m *AddGatewayInM2MServerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddGatewayInM2MServerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddGatewayInM2MServerRequest proto.InternalMessageInfo

func (m *AddGatewayInM2MServerRequest) GetOrgId() int64 {
	if m != nil {
		return m.OrgId
	}
	return 0
}

func (m *AddGatewayInM2MServerRequest) GetGwProfile() []*AppServerGatewayProfile {
	if m != nil {
		return m.GwProfile
	}
	return nil
}

type AddGatewayInM2MServerResponse struct {
	GwId                 int64            `protobuf:"varint,1,opt,name=gw_id,json=gwId,proto3" json:"gw_id,omitempty"`
	UserProfile          *ProfileResponse `protobuf:"bytes,2,opt,name=user_profile,json=userProfile,proto3" json:"user_profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *AddGatewayInM2MServerResponse) Reset()         { *m = AddGatewayInM2MServerResponse{} }
func (m *AddGatewayInM2MServerResponse) String() string { return proto.CompactTextString(m) }
func (*AddGatewayInM2MServerResponse) ProtoMessage()    {}
func (*AddGatewayInM2MServerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_19e05f446ec45efc, []int{2}
}

func (m *AddGatewayInM2MServerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddGatewayInM2MServerResponse.Unmarshal(m, b)
}
func (m *AddGatewayInM2MServerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddGatewayInM2MServerResponse.Marshal(b, m, deterministic)
}
func (m *AddGatewayInM2MServerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddGatewayInM2MServerResponse.Merge(m, src)
}
func (m *AddGatewayInM2MServerResponse) XXX_Size() int {
	return xxx_messageInfo_AddGatewayInM2MServerResponse.Size(m)
}
func (m *AddGatewayInM2MServerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddGatewayInM2MServerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddGatewayInM2MServerResponse proto.InternalMessageInfo

func (m *AddGatewayInM2MServerResponse) GetGwId() int64 {
	if m != nil {
		return m.GwId
	}
	return 0
}

func (m *AddGatewayInM2MServerResponse) GetUserProfile() *ProfileResponse {
	if m != nil {
		return m.UserProfile
	}
	return nil
}

type DeleteGatewayInM2MServerRequest struct {
	OrgId                int64    `protobuf:"varint,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	MacAddress           string   `protobuf:"bytes,2,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteGatewayInM2MServerRequest) Reset()         { *m = DeleteGatewayInM2MServerRequest{} }
func (m *DeleteGatewayInM2MServerRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteGatewayInM2MServerRequest) ProtoMessage()    {}
func (*DeleteGatewayInM2MServerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_19e05f446ec45efc, []int{3}
}

func (m *DeleteGatewayInM2MServerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteGatewayInM2MServerRequest.Unmarshal(m, b)
}
func (m *DeleteGatewayInM2MServerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteGatewayInM2MServerRequest.Marshal(b, m, deterministic)
}
func (m *DeleteGatewayInM2MServerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteGatewayInM2MServerRequest.Merge(m, src)
}
func (m *DeleteGatewayInM2MServerRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteGatewayInM2MServerRequest.Size(m)
}
func (m *DeleteGatewayInM2MServerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteGatewayInM2MServerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteGatewayInM2MServerRequest proto.InternalMessageInfo

func (m *DeleteGatewayInM2MServerRequest) GetOrgId() int64 {
	if m != nil {
		return m.OrgId
	}
	return 0
}

func (m *DeleteGatewayInM2MServerRequest) GetMacAddress() string {
	if m != nil {
		return m.MacAddress
	}
	return ""
}

type DeleteGatewayInM2MServerResponse struct {
	Status               bool             `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	UserProfile          *ProfileResponse `protobuf:"bytes,2,opt,name=user_profile,json=userProfile,proto3" json:"user_profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *DeleteGatewayInM2MServerResponse) Reset()         { *m = DeleteGatewayInM2MServerResponse{} }
func (m *DeleteGatewayInM2MServerResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteGatewayInM2MServerResponse) ProtoMessage()    {}
func (*DeleteGatewayInM2MServerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_19e05f446ec45efc, []int{4}
}

func (m *DeleteGatewayInM2MServerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteGatewayInM2MServerResponse.Unmarshal(m, b)
}
func (m *DeleteGatewayInM2MServerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteGatewayInM2MServerResponse.Marshal(b, m, deterministic)
}
func (m *DeleteGatewayInM2MServerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteGatewayInM2MServerResponse.Merge(m, src)
}
func (m *DeleteGatewayInM2MServerResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteGatewayInM2MServerResponse.Size(m)
}
func (m *DeleteGatewayInM2MServerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteGatewayInM2MServerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteGatewayInM2MServerResponse proto.InternalMessageInfo

func (m *DeleteGatewayInM2MServerResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *DeleteGatewayInM2MServerResponse) GetUserProfile() *ProfileResponse {
	if m != nil {
		return m.UserProfile
	}
	return nil
}

func init() {
	proto.RegisterType((*AppServerGatewayProfile)(nil), "api.AppServerGatewayProfile")
	proto.RegisterType((*AddGatewayInM2MServerRequest)(nil), "api.AddGatewayInM2MServerRequest")
	proto.RegisterType((*AddGatewayInM2MServerResponse)(nil), "api.AddGatewayInM2MServerResponse")
	proto.RegisterType((*DeleteGatewayInM2MServerRequest)(nil), "api.DeleteGatewayInM2MServerRequest")
	proto.RegisterType((*DeleteGatewayInM2MServerResponse)(nil), "api.DeleteGatewayInM2MServerResponse")
}

func init() { proto.RegisterFile("inner_gateway.proto", fileDescriptor_19e05f446ec45efc) }

var fileDescriptor_19e05f446ec45efc = []byte{
	// 403 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0xc1, 0x8e, 0xd3, 0x30,
	0x10, 0x86, 0x95, 0x4d, 0x5b, 0x6d, 0x27, 0x8b, 0x04, 0x5e, 0x16, 0xa2, 0xb2, 0x68, 0x43, 0x04,
	0x52, 0x4f, 0x3d, 0x84, 0x03, 0x07, 0x4e, 0x91, 0x90, 0x50, 0x0f, 0x91, 0x50, 0xf6, 0xc4, 0x85,
	0xc8, 0xc4, 0x83, 0x65, 0xa9, 0x71, 0x8c, 0xed, 0x12, 0xf1, 0x64, 0xbc, 0x0c, 0x0f, 0x83, 0x62,
	0x7b, 0x45, 0x0e, 0x64, 0x2b, 0xf6, 0x36, 0xfd, 0xe7, 0xf7, 0x7c, 0xfd, 0x67, 0x14, 0xb8, 0x14,
	0x52, 0xa2, 0x6e, 0x38, 0xb5, 0x38, 0xd0, 0x9f, 0x3b, 0xa5, 0x7b, 0xdb, 0x93, 0x98, 0x2a, 0xb1,
	0x79, 0xa4, 0x74, 0xff, 0x4d, 0x1c, 0xd0, 0x6b, 0xf9, 0xaf, 0x08, 0x9e, 0x97, 0x4a, 0xdd, 0xa2,
	0xfe, 0x81, 0xfa, 0xa3, 0xb7, 0x7f, 0xf2, 0x0e, 0xf2, 0x18, 0xe2, 0x8e, 0xb6, 0x69, 0x94, 0x45,
	0xdb, 0x75, 0x3d, 0x96, 0xe4, 0x05, 0xac, 0x5b, 0x8d, 0xd4, 0x62, 0x43, 0x6d, 0x7a, 0xe6, 0xf4,
	0x73, 0x2f, 0x94, 0x96, 0x64, 0x70, 0x71, 0xa0, 0xc6, 0x36, 0x06, 0x51, 0x8e, 0xfd, 0xd8, 0xf5,
	0x61, 0xd4, 0x6e, 0x11, 0x65, 0x69, 0xc9, 0x15, 0xac, 0x7a, 0xcd, 0x1b, 0xc1, 0xd2, 0x45, 0x16,
	0x6d, 0xe3, 0x7a, 0xd9, 0x6b, 0xbe, 0x67, 0x24, 0x83, 0x84, 0xa1, 0x69, 0xb5, 0x50, 0x56, 0xf4,
	0x32, 0x5d, 0xba, 0x77, 0x53, 0x89, 0x10, 0x58, 0x48, 0xda, 0x61, 0xba, 0x72, 0x2d, 0x57, 0xe7,
	0x1a, 0xae, 0x4b, 0xc6, 0xc2, 0x5f, 0xde, 0xcb, 0xaa, 0xa8, 0x7c, 0x88, 0x1a, 0xbf, 0x1f, 0xd1,
	0x4c, 0x61, 0xd1, 0x14, 0xf6, 0x1e, 0x80, 0x0f, 0x4d, 0x58, 0x42, 0x7a, 0x96, 0xc5, 0xdb, 0xa4,
	0xb8, 0xde, 0x51, 0x25, 0x76, 0x33, 0x6b, 0xa8, 0xd7, 0x7c, 0x08, 0x65, 0xde, 0xc1, 0xcb, 0x19,
	0xa6, 0x51, 0xbd, 0x34, 0x48, 0x2e, 0x61, 0xc9, 0x87, 0xbf, 0xcc, 0x05, 0x1f, 0xf6, 0x8c, 0xbc,
	0x83, 0x8b, 0xa3, 0x41, 0x3d, 0x81, 0x46, 0xdb, 0xa4, 0x78, 0xea, 0xa0, 0x77, 0x90, 0x30, 0xa0,
	0x4e, 0x46, 0xe7, 0x1d, 0xee, 0x33, 0xdc, 0x7c, 0xc0, 0x03, 0x5a, 0xfc, 0xef, 0x94, 0x37, 0x90,
	0x74, 0xb4, 0x6d, 0x28, 0x63, 0x1a, 0x8d, 0x09, 0xa7, 0x82, 0x8e, 0xb6, 0xa5, 0x57, 0x72, 0x03,
	0xd9, 0xfc, 0xe8, 0x10, 0xe6, 0x19, 0xac, 0x8c, 0xa5, 0xf6, 0x68, 0xdc, 0xec, 0xf3, 0x3a, 0xfc,
	0x7a, 0x70, 0x9e, 0xe2, 0x77, 0x04, 0x4f, 0xaa, 0xa2, 0x0a, 0xc8, 0x91, 0x26, 0x5a, 0x24, 0x5f,
	0xe0, 0xea, 0x9f, 0x4b, 0x25, 0xaf, 0xfc, 0x59, 0xee, 0x39, 0xf2, 0x26, 0xbf, 0xcf, 0x12, 0x62,
	0x70, 0x48, 0xe7, 0xa2, 0x92, 0xd7, 0xee, 0xfd, 0x89, 0x25, 0x6f, 0xde, 0x9c, 0x70, 0x79, 0xd0,
	0xd7, 0x95, 0xfb, 0xa4, 0xde, 0xfe, 0x09, 0x00, 0x00, 0xff, 0xff, 0xeb, 0x59, 0xb2, 0xeb, 0x7d,
	0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// M2MGatewayServiceClient is the client API for M2MGatewayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type M2MGatewayServiceClient interface {
	AddGatewayInM2MServer(ctx context.Context, in *AddGatewayInM2MServerRequest, opts ...grpc.CallOption) (*AddGatewayInM2MServerResponse, error)
	DeleteGatewayInM2MServer(ctx context.Context, in *DeleteGatewayInM2MServerRequest, opts ...grpc.CallOption) (*DeleteGatewayInM2MServerResponse, error)
}

type m2MGatewayServiceClient struct {
	cc *grpc.ClientConn
}

func NewM2MGatewayServiceClient(cc *grpc.ClientConn) M2MGatewayServiceClient {
	return &m2MGatewayServiceClient{cc}
}

func (c *m2MGatewayServiceClient) AddGatewayInM2MServer(ctx context.Context, in *AddGatewayInM2MServerRequest, opts ...grpc.CallOption) (*AddGatewayInM2MServerResponse, error) {
	out := new(AddGatewayInM2MServerResponse)
	err := c.cc.Invoke(ctx, "/api.M2MGatewayService/AddGatewayInM2MServer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *m2MGatewayServiceClient) DeleteGatewayInM2MServer(ctx context.Context, in *DeleteGatewayInM2MServerRequest, opts ...grpc.CallOption) (*DeleteGatewayInM2MServerResponse, error) {
	out := new(DeleteGatewayInM2MServerResponse)
	err := c.cc.Invoke(ctx, "/api.M2MGatewayService/DeleteGatewayInM2MServer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// M2MGatewayServiceServer is the server API for M2MGatewayService service.
type M2MGatewayServiceServer interface {
	AddGatewayInM2MServer(context.Context, *AddGatewayInM2MServerRequest) (*AddGatewayInM2MServerResponse, error)
	DeleteGatewayInM2MServer(context.Context, *DeleteGatewayInM2MServerRequest) (*DeleteGatewayInM2MServerResponse, error)
}

// UnimplementedM2MGatewayServiceServer can be embedded to have forward compatible implementations.
type UnimplementedM2MGatewayServiceServer struct {
}

func (*UnimplementedM2MGatewayServiceServer) AddGatewayInM2MServer(ctx context.Context, req *AddGatewayInM2MServerRequest) (*AddGatewayInM2MServerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddGatewayInM2MServer not implemented")
}
func (*UnimplementedM2MGatewayServiceServer) DeleteGatewayInM2MServer(ctx context.Context, req *DeleteGatewayInM2MServerRequest) (*DeleteGatewayInM2MServerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteGatewayInM2MServer not implemented")
}

func RegisterM2MGatewayServiceServer(s *grpc.Server, srv M2MGatewayServiceServer) {
	s.RegisterService(&_M2MGatewayService_serviceDesc, srv)
}

func _M2MGatewayService_AddGatewayInM2MServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddGatewayInM2MServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(M2MGatewayServiceServer).AddGatewayInM2MServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.M2MGatewayService/AddGatewayInM2MServer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(M2MGatewayServiceServer).AddGatewayInM2MServer(ctx, req.(*AddGatewayInM2MServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _M2MGatewayService_DeleteGatewayInM2MServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteGatewayInM2MServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(M2MGatewayServiceServer).DeleteGatewayInM2MServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.M2MGatewayService/DeleteGatewayInM2MServer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(M2MGatewayServiceServer).DeleteGatewayInM2MServer(ctx, req.(*DeleteGatewayInM2MServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _M2MGatewayService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.M2MGatewayService",
	HandlerType: (*M2MGatewayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddGatewayInM2MServer",
			Handler:    _M2MGatewayService_AddGatewayInM2MServer_Handler,
		},
		{
			MethodName: "DeleteGatewayInM2MServer",
			Handler:    _M2MGatewayService_DeleteGatewayInM2MServer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "inner_gateway.proto",
}
