// Code generated by protoc-gen-go. DO NOT EDIT.
// source: inner_device.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AddDeviceRequest struct {
	OrgId                int64            `protobuf:"varint,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	DevProfile           []*DeviceProfile `protobuf:"bytes,2,rep,name=dev_profile,json=devProfile,proto3" json:"dev_profile,omitempty"`
	MacAddress           string           `protobuf:"bytes,3,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *AddDeviceRequest) Reset()         { *m = AddDeviceRequest{} }
func (m *AddDeviceRequest) String() string { return proto.CompactTextString(m) }
func (*AddDeviceRequest) ProtoMessage()    {}
func (*AddDeviceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_06b99fe8ee14f928, []int{0}
}

func (m *AddDeviceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddDeviceRequest.Unmarshal(m, b)
}
func (m *AddDeviceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddDeviceRequest.Marshal(b, m, deterministic)
}
func (m *AddDeviceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddDeviceRequest.Merge(m, src)
}
func (m *AddDeviceRequest) XXX_Size() int {
	return xxx_messageInfo_AddDeviceRequest.Size(m)
}
func (m *AddDeviceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddDeviceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddDeviceRequest proto.InternalMessageInfo

func (m *AddDeviceRequest) GetOrgId() int64 {
	if m != nil {
		return m.OrgId
	}
	return 0
}

func (m *AddDeviceRequest) GetDevProfile() []*DeviceProfile {
	if m != nil {
		return m.DevProfile
	}
	return nil
}

func (m *AddDeviceRequest) GetMacAddress() string {
	if m != nil {
		return m.MacAddress
	}
	return ""
}

type AddDeviceResponse struct {
	DevId                int64            `protobuf:"varint,1,opt,name=dev_id,json=devId,proto3" json:"dev_id,omitempty"`
	UserProfile          *ProfileResponse `protobuf:"bytes,2,opt,name=user_profile,json=userProfile,proto3" json:"user_profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *AddDeviceResponse) Reset()         { *m = AddDeviceResponse{} }
func (m *AddDeviceResponse) String() string { return proto.CompactTextString(m) }
func (*AddDeviceResponse) ProtoMessage()    {}
func (*AddDeviceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_06b99fe8ee14f928, []int{1}
}

func (m *AddDeviceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddDeviceResponse.Unmarshal(m, b)
}
func (m *AddDeviceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddDeviceResponse.Marshal(b, m, deterministic)
}
func (m *AddDeviceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddDeviceResponse.Merge(m, src)
}
func (m *AddDeviceResponse) XXX_Size() int {
	return xxx_messageInfo_AddDeviceResponse.Size(m)
}
func (m *AddDeviceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddDeviceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddDeviceResponse proto.InternalMessageInfo

func (m *AddDeviceResponse) GetDevId() int64 {
	if m != nil {
		return m.DevId
	}
	return 0
}

func (m *AddDeviceResponse) GetUserProfile() *ProfileResponse {
	if m != nil {
		return m.UserProfile
	}
	return nil
}

type DeleteDeviceRequest struct {
	OrgId                int64    `protobuf:"varint,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	MacAddress           string   `protobuf:"bytes,2,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteDeviceRequest) Reset()         { *m = DeleteDeviceRequest{} }
func (m *DeleteDeviceRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteDeviceRequest) ProtoMessage()    {}
func (*DeleteDeviceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_06b99fe8ee14f928, []int{2}
}

func (m *DeleteDeviceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteDeviceRequest.Unmarshal(m, b)
}
func (m *DeleteDeviceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteDeviceRequest.Marshal(b, m, deterministic)
}
func (m *DeleteDeviceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteDeviceRequest.Merge(m, src)
}
func (m *DeleteDeviceRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteDeviceRequest.Size(m)
}
func (m *DeleteDeviceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteDeviceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteDeviceRequest proto.InternalMessageInfo

func (m *DeleteDeviceRequest) GetOrgId() int64 {
	if m != nil {
		return m.OrgId
	}
	return 0
}

func (m *DeleteDeviceRequest) GetMacAddress() string {
	if m != nil {
		return m.MacAddress
	}
	return ""
}

type DeleteDeviceResponse struct {
	Status               bool             `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	UserProfile          *ProfileResponse `protobuf:"bytes,2,opt,name=user_profile,json=userProfile,proto3" json:"user_profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *DeleteDeviceResponse) Reset()         { *m = DeleteDeviceResponse{} }
func (m *DeleteDeviceResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteDeviceResponse) ProtoMessage()    {}
func (*DeleteDeviceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_06b99fe8ee14f928, []int{3}
}

func (m *DeleteDeviceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteDeviceResponse.Unmarshal(m, b)
}
func (m *DeleteDeviceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteDeviceResponse.Marshal(b, m, deterministic)
}
func (m *DeleteDeviceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteDeviceResponse.Merge(m, src)
}
func (m *DeleteDeviceResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteDeviceResponse.Size(m)
}
func (m *DeleteDeviceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteDeviceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteDeviceResponse proto.InternalMessageInfo

func (m *DeleteDeviceResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *DeleteDeviceResponse) GetUserProfile() *ProfileResponse {
	if m != nil {
		return m.UserProfile
	}
	return nil
}

func init() {
	proto.RegisterType((*AddDeviceRequest)(nil), "api.AddDeviceRequest")
	proto.RegisterType((*AddDeviceResponse)(nil), "api.AddDeviceResponse")
	proto.RegisterType((*DeleteDeviceRequest)(nil), "api.DeleteDeviceRequest")
	proto.RegisterType((*DeleteDeviceResponse)(nil), "api.DeleteDeviceResponse")
}

func init() { proto.RegisterFile("inner_device.proto", fileDescriptor_06b99fe8ee14f928) }

var fileDescriptor_06b99fe8ee14f928 = []byte{
	// 308 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xb1, 0x4e, 0xb4, 0x40,
	0x10, 0xc7, 0xc3, 0x91, 0x8f, 0x7c, 0x37, 0x60, 0xa2, 0xeb, 0xdd, 0x05, 0x69, 0x24, 0x54, 0x54,
	0x14, 0x5c, 0x61, 0x62, 0x77, 0xf1, 0x1a, 0x0a, 0x13, 0xb3, 0x3e, 0x00, 0x59, 0xd9, 0x91, 0x6c,
	0x72, 0xc7, 0xe2, 0x2e, 0xd0, 0xfa, 0x14, 0xbe, 0xaf, 0x01, 0x56, 0x45, 0xce, 0xc2, 0x58, 0xc1,
	0xfc, 0x67, 0xe6, 0x3f, 0x3f, 0x66, 0x00, 0x22, 0xaa, 0x0a, 0x55, 0xce, 0xb1, 0x13, 0x05, 0x26,
	0xb5, 0x92, 0x8d, 0x24, 0x36, 0xab, 0x45, 0xe0, 0x4d, 0xa5, 0xe0, 0xac, 0x56, 0xf2, 0x59, 0x1c,
	0x4c, 0x18, 0xbd, 0xc2, 0xf9, 0x8e, 0xf3, 0xfd, 0x50, 0x41, 0xf1, 0xa5, 0x45, 0xdd, 0x90, 0x35,
	0x38, 0x52, 0x95, 0xb9, 0xe0, 0xbe, 0x15, 0x5a, 0xb1, 0x4d, 0xff, 0x49, 0x55, 0x66, 0x9c, 0x6c,
	0xc1, 0xe5, 0xd8, 0xe5, 0xa6, 0xdf, 0x5f, 0x84, 0x76, 0xec, 0xa6, 0x24, 0x61, 0xb5, 0x48, 0xc6,
	0xfe, 0x87, 0x31, 0x43, 0x81, 0x63, 0x67, 0xde, 0xc9, 0x35, 0xb8, 0x47, 0x56, 0xe4, 0x8c, 0x73,
	0x85, 0x5a, 0xfb, 0x76, 0x68, 0xc5, 0x4b, 0x0a, 0x47, 0x56, 0xec, 0x46, 0x25, 0x2a, 0xe0, 0x62,
	0x02, 0xa0, 0x6b, 0x59, 0x69, 0xec, 0x09, 0xfa, 0x51, 0x5f, 0x04, 0x1c, 0xbb, 0x8c, 0x93, 0x1b,
	0xf0, 0x5a, 0x8d, 0x6a, 0x82, 0x60, 0xc5, 0x6e, 0xba, 0x1a, 0x10, 0x3e, 0x86, 0x1b, 0x0b, 0xea,
	0xf6, 0x95, 0x46, 0x8c, 0xee, 0xe1, 0x72, 0x8f, 0x07, 0x6c, 0xf0, 0x57, 0x1f, 0x3a, 0x63, 0x5e,
	0x9c, 0x30, 0x97, 0xb0, 0xfa, 0x6e, 0x67, 0xb0, 0x37, 0xe0, 0xe8, 0x86, 0x35, 0xad, 0x1e, 0xfc,
	0xfe, 0x53, 0x13, 0xfd, 0x99, 0x3b, 0x7d, 0xb3, 0x80, 0x64, 0xfd, 0x59, 0xc7, 0x41, 0x8f, 0xa8,
	0xfa, 0x07, 0xb9, 0x85, 0xe5, 0xe7, 0xce, 0xc8, 0x7a, 0xb0, 0x99, 0x1f, 0x31, 0xd8, 0xcc, 0x65,
	0xc3, 0x78, 0x07, 0xde, 0x94, 0x9d, 0xf8, 0xe6, 0x80, 0x27, 0xdb, 0x09, 0xae, 0x7e, 0xc8, 0x8c,
	0x26, 0x4f, 0xce, 0xf0, 0xf3, 0x6c, 0xdf, 0x03, 0x00, 0x00, 0xff, 0xff, 0xa0, 0x2d, 0x49, 0x4a,
	0x74, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// InnerDeviceServiceClient is the client API for InnerDeviceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type InnerDeviceServiceClient interface {
	AddDevice(ctx context.Context, in *AddDeviceRequest, opts ...grpc.CallOption) (*AddDeviceResponse, error)
	DeleteDevice(ctx context.Context, in *DeleteDeviceRequest, opts ...grpc.CallOption) (*DeleteDeviceResponse, error)
}

type innerDeviceServiceClient struct {
	cc *grpc.ClientConn
}

func NewInnerDeviceServiceClient(cc *grpc.ClientConn) InnerDeviceServiceClient {
	return &innerDeviceServiceClient{cc}
}

func (c *innerDeviceServiceClient) AddDevice(ctx context.Context, in *AddDeviceRequest, opts ...grpc.CallOption) (*AddDeviceResponse, error) {
	out := new(AddDeviceResponse)
	err := c.cc.Invoke(ctx, "/api.InnerDeviceService/AddDevice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *innerDeviceServiceClient) DeleteDevice(ctx context.Context, in *DeleteDeviceRequest, opts ...grpc.CallOption) (*DeleteDeviceResponse, error) {
	out := new(DeleteDeviceResponse)
	err := c.cc.Invoke(ctx, "/api.InnerDeviceService/DeleteDevice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InnerDeviceServiceServer is the server API for InnerDeviceService service.
type InnerDeviceServiceServer interface {
	AddDevice(context.Context, *AddDeviceRequest) (*AddDeviceResponse, error)
	DeleteDevice(context.Context, *DeleteDeviceRequest) (*DeleteDeviceResponse, error)
}

// UnimplementedInnerDeviceServiceServer can be embedded to have forward compatible implementations.
type UnimplementedInnerDeviceServiceServer struct {
}

func (*UnimplementedInnerDeviceServiceServer) AddDevice(ctx context.Context, req *AddDeviceRequest) (*AddDeviceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddDevice not implemented")
}
func (*UnimplementedInnerDeviceServiceServer) DeleteDevice(ctx context.Context, req *DeleteDeviceRequest) (*DeleteDeviceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDevice not implemented")
}

func RegisterInnerDeviceServiceServer(s *grpc.Server, srv InnerDeviceServiceServer) {
	s.RegisterService(&_InnerDeviceService_serviceDesc, srv)
}

func _InnerDeviceService_AddDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InnerDeviceServiceServer).AddDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.InnerDeviceService/AddDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InnerDeviceServiceServer).AddDevice(ctx, req.(*AddDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InnerDeviceService_DeleteDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InnerDeviceServiceServer).DeleteDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.InnerDeviceService/DeleteDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InnerDeviceServiceServer).DeleteDevice(ctx, req.(*DeleteDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _InnerDeviceService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.InnerDeviceService",
	HandlerType: (*InnerDeviceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddDevice",
			Handler:    _InnerDeviceService_AddDevice_Handler,
		},
		{
			MethodName: "DeleteDevice",
			Handler:    _InnerDeviceService_DeleteDevice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "inner_device.proto",
}
