#!/bin/sh

echo "running script: sync_cors_allow_origin "

M2M_PATH=$(dirname $0)/..
ENV_CONFIGURATION=$M2M_PATH/ui/.env.production

if [ -f $ENV_CONFIGURATION ]; then
  APPSERVER=$(cat $ENV_CONFIGURATION | awk -F "=" '/REACT_APP_LORA_APP_SERVER/{print $2}')
  echo "### appserver = $APPSERVER"
fi

CONFIGURATION=$M2M_PATH/../configuration/mxprotocol-server.toml

if [ -f $CONFIGURATION ]; then
  echo "### sed -i.bak 's,^cors_allow_origin=.*$,cors_allow_origin='"$APPSERVER"',' $CONFIGURATION"
  sed -i.bak 's,^cors_allow_origin=.*$,cors_allow_origin='"$APPSERVER"',' $CONFIGURATION
  cp $CONFIGURATION /etc/mxprotocol-server
fi