// Code generated by protoc-gen-go. DO NOT EDIT.
// source: wallet.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetWalletBalanceRequest struct {
	OrgId                int64    `protobuf:"varint,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetWalletBalanceRequest) Reset()         { *m = GetWalletBalanceRequest{} }
func (m *GetWalletBalanceRequest) String() string { return proto.CompactTextString(m) }
func (*GetWalletBalanceRequest) ProtoMessage()    {}
func (*GetWalletBalanceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b88fd140af4deb6f, []int{0}
}

func (m *GetWalletBalanceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWalletBalanceRequest.Unmarshal(m, b)
}
func (m *GetWalletBalanceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWalletBalanceRequest.Marshal(b, m, deterministic)
}
func (m *GetWalletBalanceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWalletBalanceRequest.Merge(m, src)
}
func (m *GetWalletBalanceRequest) XXX_Size() int {
	return xxx_messageInfo_GetWalletBalanceRequest.Size(m)
}
func (m *GetWalletBalanceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWalletBalanceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetWalletBalanceRequest proto.InternalMessageInfo

func (m *GetWalletBalanceRequest) GetOrgId() int64 {
	if m != nil {
		return m.OrgId
	}
	return 0
}

type GetWalletBalanceResponse struct {
	Balance              float64          `protobuf:"fixed64,1,opt,name=balance,proto3" json:"balance,omitempty"`
	UserProfile          *ProfileResponse `protobuf:"bytes,2,opt,name=user_profile,json=userProfile,proto3" json:"user_profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetWalletBalanceResponse) Reset()         { *m = GetWalletBalanceResponse{} }
func (m *GetWalletBalanceResponse) String() string { return proto.CompactTextString(m) }
func (*GetWalletBalanceResponse) ProtoMessage()    {}
func (*GetWalletBalanceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b88fd140af4deb6f, []int{1}
}

func (m *GetWalletBalanceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWalletBalanceResponse.Unmarshal(m, b)
}
func (m *GetWalletBalanceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWalletBalanceResponse.Marshal(b, m, deterministic)
}
func (m *GetWalletBalanceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWalletBalanceResponse.Merge(m, src)
}
func (m *GetWalletBalanceResponse) XXX_Size() int {
	return xxx_messageInfo_GetWalletBalanceResponse.Size(m)
}
func (m *GetWalletBalanceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWalletBalanceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetWalletBalanceResponse proto.InternalMessageInfo

func (m *GetWalletBalanceResponse) GetBalance() float64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *GetWalletBalanceResponse) GetUserProfile() *ProfileResponse {
	if m != nil {
		return m.UserProfile
	}
	return nil
}

type GetVmxcTxHistoryRequest struct {
	OrgId                int64    `protobuf:"varint,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Offset               int64    `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                int64    `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetVmxcTxHistoryRequest) Reset()         { *m = GetVmxcTxHistoryRequest{} }
func (m *GetVmxcTxHistoryRequest) String() string { return proto.CompactTextString(m) }
func (*GetVmxcTxHistoryRequest) ProtoMessage()    {}
func (*GetVmxcTxHistoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b88fd140af4deb6f, []int{2}
}

func (m *GetVmxcTxHistoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVmxcTxHistoryRequest.Unmarshal(m, b)
}
func (m *GetVmxcTxHistoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVmxcTxHistoryRequest.Marshal(b, m, deterministic)
}
func (m *GetVmxcTxHistoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVmxcTxHistoryRequest.Merge(m, src)
}
func (m *GetVmxcTxHistoryRequest) XXX_Size() int {
	return xxx_messageInfo_GetVmxcTxHistoryRequest.Size(m)
}
func (m *GetVmxcTxHistoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVmxcTxHistoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetVmxcTxHistoryRequest proto.InternalMessageInfo

func (m *GetVmxcTxHistoryRequest) GetOrgId() int64 {
	if m != nil {
		return m.OrgId
	}
	return 0
}

func (m *GetVmxcTxHistoryRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *GetVmxcTxHistoryRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type VmxcTxHistory struct {
	From                 string   `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To                   string   `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	TxType               string   `protobuf:"bytes,3,opt,name=tx_type,json=txType,proto3" json:"tx_type,omitempty"`
	Amount               float64  `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	CreatedAt            string   `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VmxcTxHistory) Reset()         { *m = VmxcTxHistory{} }
func (m *VmxcTxHistory) String() string { return proto.CompactTextString(m) }
func (*VmxcTxHistory) ProtoMessage()    {}
func (*VmxcTxHistory) Descriptor() ([]byte, []int) {
	return fileDescriptor_b88fd140af4deb6f, []int{3}
}

func (m *VmxcTxHistory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VmxcTxHistory.Unmarshal(m, b)
}
func (m *VmxcTxHistory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VmxcTxHistory.Marshal(b, m, deterministic)
}
func (m *VmxcTxHistory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VmxcTxHistory.Merge(m, src)
}
func (m *VmxcTxHistory) XXX_Size() int {
	return xxx_messageInfo_VmxcTxHistory.Size(m)
}
func (m *VmxcTxHistory) XXX_DiscardUnknown() {
	xxx_messageInfo_VmxcTxHistory.DiscardUnknown(m)
}

var xxx_messageInfo_VmxcTxHistory proto.InternalMessageInfo

func (m *VmxcTxHistory) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *VmxcTxHistory) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *VmxcTxHistory) GetTxType() string {
	if m != nil {
		return m.TxType
	}
	return ""
}

func (m *VmxcTxHistory) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *VmxcTxHistory) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

type GetVmxcTxHistoryResponse struct {
	Count                int64            `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	TxHistory            []*VmxcTxHistory `protobuf:"bytes,2,rep,name=tx_history,json=txHistory,proto3" json:"tx_history,omitempty"`
	UserProfile          *ProfileResponse `protobuf:"bytes,3,opt,name=user_profile,json=userProfile,proto3" json:"user_profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetVmxcTxHistoryResponse) Reset()         { *m = GetVmxcTxHistoryResponse{} }
func (m *GetVmxcTxHistoryResponse) String() string { return proto.CompactTextString(m) }
func (*GetVmxcTxHistoryResponse) ProtoMessage()    {}
func (*GetVmxcTxHistoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b88fd140af4deb6f, []int{4}
}

func (m *GetVmxcTxHistoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVmxcTxHistoryResponse.Unmarshal(m, b)
}
func (m *GetVmxcTxHistoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVmxcTxHistoryResponse.Marshal(b, m, deterministic)
}
func (m *GetVmxcTxHistoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVmxcTxHistoryResponse.Merge(m, src)
}
func (m *GetVmxcTxHistoryResponse) XXX_Size() int {
	return xxx_messageInfo_GetVmxcTxHistoryResponse.Size(m)
}
func (m *GetVmxcTxHistoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVmxcTxHistoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetVmxcTxHistoryResponse proto.InternalMessageInfo

func (m *GetVmxcTxHistoryResponse) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *GetVmxcTxHistoryResponse) GetTxHistory() []*VmxcTxHistory {
	if m != nil {
		return m.TxHistory
	}
	return nil
}

func (m *GetVmxcTxHistoryResponse) GetUserProfile() *ProfileResponse {
	if m != nil {
		return m.UserProfile
	}
	return nil
}

type GetWalletUsageHistRequest struct {
	OrgId                int64    `protobuf:"varint,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetWalletUsageHistRequest) Reset()         { *m = GetWalletUsageHistRequest{} }
func (m *GetWalletUsageHistRequest) String() string { return proto.CompactTextString(m) }
func (*GetWalletUsageHistRequest) ProtoMessage()    {}
func (*GetWalletUsageHistRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b88fd140af4deb6f, []int{5}
}

func (m *GetWalletUsageHistRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWalletUsageHistRequest.Unmarshal(m, b)
}
func (m *GetWalletUsageHistRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWalletUsageHistRequest.Marshal(b, m, deterministic)
}
func (m *GetWalletUsageHistRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWalletUsageHistRequest.Merge(m, src)
}
func (m *GetWalletUsageHistRequest) XXX_Size() int {
	return xxx_messageInfo_GetWalletUsageHistRequest.Size(m)
}
func (m *GetWalletUsageHistRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWalletUsageHistRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetWalletUsageHistRequest proto.InternalMessageInfo

func (m *GetWalletUsageHistRequest) GetOrgId() int64 {
	if m != nil {
		return m.OrgId
	}
	return 0
}

type GetWalletUsageHist struct {
	StartTime            string   `protobuf:"bytes,1,opt,name=StartTime,proto3" json:"StartTime,omitempty"`
	Duration             string   `protobuf:"bytes,2,opt,name=Duration,proto3" json:"Duration,omitempty"`
	CountUplinkPktsDv    int64    `protobuf:"varint,3,opt,name=CountUplinkPktsDv,proto3" json:"CountUplinkPktsDv,omitempty"`
	CountDownlinkPktsDv  int64    `protobuf:"varint,4,opt,name=CountDownlinkPktsDv,proto3" json:"CountDownlinkPktsDv,omitempty"`
	CountUplinkPktsGw    int64    `protobuf:"varint,5,opt,name=CountUplinkPktsGw,proto3" json:"CountUplinkPktsGw,omitempty"`
	CountDownlinkPktsGw  int64    `protobuf:"varint,6,opt,name=CountDownlinkPktsGw,proto3" json:"CountDownlinkPktsGw,omitempty"`
	Cost                 float64  `protobuf:"fixed64,7,opt,name=Cost,proto3" json:"Cost,omitempty"`
	Income               float64  `protobuf:"fixed64,8,opt,name=Income,proto3" json:"Income,omitempty"`
	TotalPayment         float64  `protobuf:"fixed64,9,opt,name=TotalPayment,proto3" json:"TotalPayment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetWalletUsageHist) Reset()         { *m = GetWalletUsageHist{} }
func (m *GetWalletUsageHist) String() string { return proto.CompactTextString(m) }
func (*GetWalletUsageHist) ProtoMessage()    {}
func (*GetWalletUsageHist) Descriptor() ([]byte, []int) {
	return fileDescriptor_b88fd140af4deb6f, []int{6}
}

func (m *GetWalletUsageHist) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWalletUsageHist.Unmarshal(m, b)
}
func (m *GetWalletUsageHist) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWalletUsageHist.Marshal(b, m, deterministic)
}
func (m *GetWalletUsageHist) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWalletUsageHist.Merge(m, src)
}
func (m *GetWalletUsageHist) XXX_Size() int {
	return xxx_messageInfo_GetWalletUsageHist.Size(m)
}
func (m *GetWalletUsageHist) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWalletUsageHist.DiscardUnknown(m)
}

var xxx_messageInfo_GetWalletUsageHist proto.InternalMessageInfo

func (m *GetWalletUsageHist) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

func (m *GetWalletUsageHist) GetDuration() string {
	if m != nil {
		return m.Duration
	}
	return ""
}

func (m *GetWalletUsageHist) GetCountUplinkPktsDv() int64 {
	if m != nil {
		return m.CountUplinkPktsDv
	}
	return 0
}

func (m *GetWalletUsageHist) GetCountDownlinkPktsDv() int64 {
	if m != nil {
		return m.CountDownlinkPktsDv
	}
	return 0
}

func (m *GetWalletUsageHist) GetCountUplinkPktsGw() int64 {
	if m != nil {
		return m.CountUplinkPktsGw
	}
	return 0
}

func (m *GetWalletUsageHist) GetCountDownlinkPktsGw() int64 {
	if m != nil {
		return m.CountDownlinkPktsGw
	}
	return 0
}

func (m *GetWalletUsageHist) GetCost() float64 {
	if m != nil {
		return m.Cost
	}
	return 0
}

func (m *GetWalletUsageHist) GetIncome() float64 {
	if m != nil {
		return m.Income
	}
	return 0
}

func (m *GetWalletUsageHist) GetTotalPayment() float64 {
	if m != nil {
		return m.TotalPayment
	}
	return 0
}

type GetWalletUsageHistResponse struct {
	WalletUsageHis       []*GetWalletUsageHist `protobuf:"bytes,1,rep,name=wallet_usage_his,json=walletUsageHis,proto3" json:"wallet_usage_his,omitempty"`
	UserProfile          *ProfileResponse      `protobuf:"bytes,2,opt,name=user_profile,json=userProfile,proto3" json:"user_profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *GetWalletUsageHistResponse) Reset()         { *m = GetWalletUsageHistResponse{} }
func (m *GetWalletUsageHistResponse) String() string { return proto.CompactTextString(m) }
func (*GetWalletUsageHistResponse) ProtoMessage()    {}
func (*GetWalletUsageHistResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b88fd140af4deb6f, []int{7}
}

func (m *GetWalletUsageHistResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWalletUsageHistResponse.Unmarshal(m, b)
}
func (m *GetWalletUsageHistResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWalletUsageHistResponse.Marshal(b, m, deterministic)
}
func (m *GetWalletUsageHistResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWalletUsageHistResponse.Merge(m, src)
}
func (m *GetWalletUsageHistResponse) XXX_Size() int {
	return xxx_messageInfo_GetWalletUsageHistResponse.Size(m)
}
func (m *GetWalletUsageHistResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWalletUsageHistResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetWalletUsageHistResponse proto.InternalMessageInfo

func (m *GetWalletUsageHistResponse) GetWalletUsageHis() []*GetWalletUsageHist {
	if m != nil {
		return m.WalletUsageHis
	}
	return nil
}

func (m *GetWalletUsageHistResponse) GetUserProfile() *ProfileResponse {
	if m != nil {
		return m.UserProfile
	}
	return nil
}

func init() {
	proto.RegisterType((*GetWalletBalanceRequest)(nil), "api.GetWalletBalanceRequest")
	proto.RegisterType((*GetWalletBalanceResponse)(nil), "api.GetWalletBalanceResponse")
	proto.RegisterType((*GetVmxcTxHistoryRequest)(nil), "api.GetVmxcTxHistoryRequest")
	proto.RegisterType((*VmxcTxHistory)(nil), "api.VmxcTxHistory")
	proto.RegisterType((*GetVmxcTxHistoryResponse)(nil), "api.GetVmxcTxHistoryResponse")
	proto.RegisterType((*GetWalletUsageHistRequest)(nil), "api.GetWalletUsageHistRequest")
	proto.RegisterType((*GetWalletUsageHist)(nil), "api.GetWalletUsageHist")
	proto.RegisterType((*GetWalletUsageHistResponse)(nil), "api.GetWalletUsageHistResponse")
}

func init() { proto.RegisterFile("wallet.proto", fileDescriptor_b88fd140af4deb6f) }

var fileDescriptor_b88fd140af4deb6f = []byte{
	// 654 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x4b, 0x6f, 0xd3, 0x40,
	0x10, 0x96, 0xe3, 0x26, 0xad, 0xa7, 0x0f, 0x95, 0xa5, 0x50, 0x13, 0xa5, 0x0f, 0xac, 0x4a, 0x54,
	0x08, 0x9a, 0x12, 0x0e, 0x9c, 0x4b, 0x2b, 0x85, 0xde, 0x2a, 0x37, 0x85, 0x1b, 0xd1, 0x36, 0xdd,
	0x04, 0xab, 0xb6, 0xd7, 0xd8, 0x93, 0xda, 0x11, 0xe2, 0xc0, 0xe3, 0x1f, 0x70, 0xe1, 0xc0, 0xbf,
	0xe2, 0xce, 0x89, 0x1f, 0x82, 0x3c, 0xbb, 0x49, 0x71, 0xe3, 0x00, 0xe2, 0xb6, 0xf3, 0xd8, 0xef,
	0x9b, 0x9d, 0xf9, 0x76, 0x60, 0x29, 0xe5, 0xbe, 0x2f, 0x70, 0x2f, 0x8a, 0x25, 0x4a, 0x66, 0xf2,
	0xc8, 0xab, 0x37, 0x06, 0x52, 0x0e, 0x7c, 0xd1, 0xe4, 0x91, 0xd7, 0xe4, 0x61, 0x28, 0x91, 0xa3,
	0x27, 0xc3, 0x44, 0xa5, 0xd4, 0x97, 0xa3, 0x58, 0xf6, 0x3d, 0x5f, 0x28, 0xd3, 0xd9, 0x87, 0xf5,
	0xb6, 0xc0, 0x57, 0x04, 0xf2, 0x9c, 0xfb, 0x3c, 0xec, 0x09, 0x57, 0xbc, 0x1d, 0x8a, 0x04, 0xd9,
	0x1d, 0xa8, 0xc9, 0x78, 0xd0, 0xf5, 0x2e, 0x6c, 0x63, 0xdb, 0xd8, 0x35, 0xdd, 0xaa, 0x8c, 0x07,
	0xc7, 0x17, 0x4e, 0x00, 0xf6, 0xf4, 0x8d, 0x24, 0x92, 0x61, 0x22, 0x98, 0x0d, 0xf3, 0xe7, 0xca,
	0x45, 0x77, 0x0c, 0x77, 0x6c, 0xb2, 0x67, 0xb0, 0x34, 0x4c, 0x44, 0xdc, 0xd5, 0xec, 0x76, 0x65,
	0xdb, 0xd8, 0x5d, 0x6c, 0xad, 0xed, 0xf1, 0xc8, 0xdb, 0x3b, 0x51, 0xbe, 0x31, 0x8a, 0xbb, 0x98,
	0x67, 0x6a, 0xa7, 0xf3, 0x9a, 0x0a, 0x7c, 0x19, 0x64, 0xbd, 0x4e, 0xf6, 0xc2, 0x4b, 0x50, 0xc6,
	0xa3, 0x3f, 0x17, 0xc8, 0xee, 0x42, 0x4d, 0xf6, 0xfb, 0x89, 0x40, 0x22, 0x31, 0x5d, 0x6d, 0xb1,
	0x35, 0xa8, 0xfa, 0x5e, 0xe0, 0xa1, 0x6d, 0xaa, 0x6c, 0x32, 0x9c, 0x4f, 0x06, 0x2c, 0x17, 0xd0,
	0x19, 0x83, 0xb9, 0x7e, 0x2c, 0x03, 0x02, 0xb5, 0x5c, 0x3a, 0xb3, 0x15, 0xa8, 0xa0, 0x24, 0x3c,
	0xcb, 0xad, 0xa0, 0x64, 0xeb, 0x30, 0x8f, 0x59, 0x17, 0x47, 0x91, 0x20, 0x34, 0xcb, 0xad, 0x61,
	0xd6, 0x19, 0x45, 0x22, 0x27, 0xe7, 0x81, 0x1c, 0x86, 0x68, 0xcf, 0x51, 0x03, 0xb4, 0xc5, 0x36,
	0x00, 0x7a, 0xb1, 0xe0, 0x28, 0x2e, 0xba, 0x1c, 0xed, 0x2a, 0xdd, 0xb1, 0xb4, 0xe7, 0x00, 0x9d,
	0x6f, 0x06, 0x75, 0xf5, 0xc6, 0x33, 0x75, 0x57, 0xd7, 0xa0, 0xda, 0x23, 0x48, 0xfd, 0x4c, 0x32,
	0xd8, 0x13, 0x00, 0xcc, 0xba, 0x6f, 0x54, 0xae, 0x5d, 0xd9, 0x36, 0x77, 0x17, 0x5b, 0x8c, 0xfa,
	0x59, 0x44, 0xb1, 0x70, 0xf2, 0xb2, 0x9b, 0x43, 0x30, 0xff, 0x75, 0x08, 0x2d, 0xb8, 0x37, 0x99,
	0xf9, 0x59, 0xc2, 0x07, 0x22, 0x47, 0xfc, 0x8b, 0x4e, 0x7e, 0x54, 0x80, 0x4d, 0x5f, 0x62, 0x0d,
	0xb0, 0x4e, 0x91, 0xc7, 0xd8, 0xf1, 0x02, 0xa1, 0x5b, 0x7c, 0xed, 0x60, 0x75, 0x58, 0x38, 0x1a,
	0xc6, 0x24, 0x58, 0xdd, 0xed, 0x89, 0xcd, 0x1e, 0xc1, 0xad, 0xc3, 0xfc, 0xe5, 0x67, 0x91, 0xef,
	0x85, 0x97, 0x27, 0x97, 0x98, 0x1c, 0x5d, 0xe9, 0x59, 0x4e, 0x07, 0xd8, 0x3e, 0xdc, 0x26, 0xe7,
	0x91, 0x4c, 0xc3, 0xdf, 0xf2, 0xe7, 0x28, 0xbf, 0x2c, 0x54, 0x82, 0xdf, 0x4e, 0x69, 0x52, 0xd3,
	0xf8, 0xed, 0xb4, 0x14, 0xbf, 0x9d, 0xda, 0xb5, 0x19, 0xf8, 0xed, 0x34, 0xd7, 0xd5, 0xa1, 0x4c,
	0xd0, 0x9e, 0x27, 0x61, 0xd0, 0x39, 0x97, 0xcb, 0x71, 0xd8, 0x93, 0x81, 0xb0, 0x17, 0x94, 0x5c,
	0x94, 0xc5, 0x1c, 0x58, 0xea, 0x48, 0xe4, 0xfe, 0x09, 0x1f, 0x05, 0x22, 0x44, 0xdb, 0xa2, 0x68,
	0xc1, 0xe7, 0x7c, 0x35, 0xa0, 0x5e, 0x36, 0x15, 0xad, 0x9a, 0x03, 0x58, 0x55, 0xbb, 0xa1, 0x3b,
	0xcc, 0x63, 0xb9, 0x52, 0x6c, 0x83, 0x54, 0xb2, 0x4e, 0x03, 0x2f, 0xb9, 0xba, 0x92, 0x16, 0x1c,
	0xff, 0xfd, 0x69, 0x5b, 0x9f, 0x4d, 0x58, 0x56, 0xe0, 0xa7, 0x22, 0xbe, 0xf2, 0x7a, 0x82, 0x0d,
	0x61, 0xf5, 0xe6, 0xd6, 0x60, 0x8d, 0x62, 0x1d, 0xc5, 0xf5, 0x53, 0xdf, 0x98, 0x11, 0x55, 0x7c,
	0xce, 0xce, 0xc7, 0xef, 0x3f, 0xbf, 0x54, 0x36, 0x59, 0x83, 0xf6, 0x9c, 0x2a, 0xbc, 0xf9, 0x4e,
	0x09, 0xf1, 0x7d, 0x73, 0xbc, 0x76, 0x32, 0xa2, 0x2d, 0xfe, 0xef, 0x09, 0x6d, 0xd9, 0x52, 0xb9,
	0xa6, 0x2d, 0xfd, 0x8b, 0xce, 0x03, 0xa2, 0xbd, 0xcf, 0xb6, 0x4a, 0x69, 0x31, 0x7b, 0xac, 0x3f,
	0x24, 0xfb, 0x60, 0x94, 0xca, 0x7f, 0x73, 0x56, 0xef, 0x35, 0xfd, 0xd6, 0xcc, 0xb8, 0x2e, 0xe0,
	0x21, 0x15, 0xb0, 0xc3, 0x9c, 0xd2, 0x02, 0x68, 0xd4, 0xe3, 0x1a, 0xce, 0x6b, 0xb4, 0xe3, 0x9f,
	0xfe, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x90, 0x95, 0x6f, 0xa3, 0x25, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WalletServiceClient is the client API for WalletService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WalletServiceClient interface {
	GetWalletBalance(ctx context.Context, in *GetWalletBalanceRequest, opts ...grpc.CallOption) (*GetWalletBalanceResponse, error)
	GetVmxcTxHistory(ctx context.Context, in *GetVmxcTxHistoryRequest, opts ...grpc.CallOption) (*GetVmxcTxHistoryResponse, error)
	GetWalletUsageHist(ctx context.Context, in *GetWalletUsageHistRequest, opts ...grpc.CallOption) (*GetWalletUsageHistResponse, error)
}

type walletServiceClient struct {
	cc *grpc.ClientConn
}

func NewWalletServiceClient(cc *grpc.ClientConn) WalletServiceClient {
	return &walletServiceClient{cc}
}

func (c *walletServiceClient) GetWalletBalance(ctx context.Context, in *GetWalletBalanceRequest, opts ...grpc.CallOption) (*GetWalletBalanceResponse, error) {
	out := new(GetWalletBalanceResponse)
	err := c.cc.Invoke(ctx, "/api.WalletService/GetWalletBalance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) GetVmxcTxHistory(ctx context.Context, in *GetVmxcTxHistoryRequest, opts ...grpc.CallOption) (*GetVmxcTxHistoryResponse, error) {
	out := new(GetVmxcTxHistoryResponse)
	err := c.cc.Invoke(ctx, "/api.WalletService/GetVmxcTxHistory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) GetWalletUsageHist(ctx context.Context, in *GetWalletUsageHistRequest, opts ...grpc.CallOption) (*GetWalletUsageHistResponse, error) {
	out := new(GetWalletUsageHistResponse)
	err := c.cc.Invoke(ctx, "/api.WalletService/GetWalletUsageHist", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WalletServiceServer is the server API for WalletService service.
type WalletServiceServer interface {
	GetWalletBalance(context.Context, *GetWalletBalanceRequest) (*GetWalletBalanceResponse, error)
	GetVmxcTxHistory(context.Context, *GetVmxcTxHistoryRequest) (*GetVmxcTxHistoryResponse, error)
	GetWalletUsageHist(context.Context, *GetWalletUsageHistRequest) (*GetWalletUsageHistResponse, error)
}

// UnimplementedWalletServiceServer can be embedded to have forward compatible implementations.
type UnimplementedWalletServiceServer struct {
}

func (*UnimplementedWalletServiceServer) GetWalletBalance(ctx context.Context, req *GetWalletBalanceRequest) (*GetWalletBalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWalletBalance not implemented")
}
func (*UnimplementedWalletServiceServer) GetVmxcTxHistory(ctx context.Context, req *GetVmxcTxHistoryRequest) (*GetVmxcTxHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVmxcTxHistory not implemented")
}
func (*UnimplementedWalletServiceServer) GetWalletUsageHist(ctx context.Context, req *GetWalletUsageHistRequest) (*GetWalletUsageHistResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWalletUsageHist not implemented")
}

func RegisterWalletServiceServer(s *grpc.Server, srv WalletServiceServer) {
	s.RegisterService(&_WalletService_serviceDesc, srv)
}

func _WalletService_GetWalletBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWalletBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).GetWalletBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.WalletService/GetWalletBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).GetWalletBalance(ctx, req.(*GetWalletBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_GetVmxcTxHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVmxcTxHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).GetVmxcTxHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.WalletService/GetVmxcTxHistory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).GetVmxcTxHistory(ctx, req.(*GetVmxcTxHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_GetWalletUsageHist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWalletUsageHistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).GetWalletUsageHist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.WalletService/GetWalletUsageHist",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).GetWalletUsageHist(ctx, req.(*GetWalletUsageHistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _WalletService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.WalletService",
	HandlerType: (*WalletServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetWalletBalance",
			Handler:    _WalletService_GetWalletBalance_Handler,
		},
		{
			MethodName: "GetVmxcTxHistory",
			Handler:    _WalletService_GetVmxcTxHistory_Handler,
		},
		{
			MethodName: "GetWalletUsageHist",
			Handler:    _WalletService_GetWalletUsageHist_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wallet.proto",
}
